// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class AMessage
{
    public int Pkid { get; set; }

    public int? Src { get; set; }

    public int? Threadid { get; set; }

    public int? Messageid { get; set; }

    public int? Messageid2 { get; set; }

    public string Source { get; set; }

    public int? ServiceRequestId { get; set; }

    public string SendTo { get; set; }

    public string SenderFirstName { get; set; }

    public string SenderLastName { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public int? OrganizationId { get; set; }

    public int? PhysicianId { get; set; }

    public int? PatientId { get; set; }

    public string MessageText { get; set; }
}