// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class AutoCallingBvprocessConfiguration
{
    public long AutoCallingBvprocessConfigurationId { get; set; }

    public int ProgramId { get; set; }

    public string SrtypeShortDesc { get; set; }

    public string Srresolution { get; set; }

    public bool? IsBicreateAllowed { get; set; }

    public bool? Deleted { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }

    public string DrugName { get; set; }
}