// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class BiomarinRosterStage
{
    public int RosterId { get; set; }

    public string Program { get; set; }

    public string RegionName { get; set; }

    public string RegionId { get; set; }

    public string DistrictName { get; set; }

    public string DistrictId { get; set; }

    public string TerritoryName { get; set; }

    public string TerritoryId { get; set; }

    public string Email { get; set; }

    public string First { get; set; }

    public string Last { get; set; }

    public string Gender { get; set; }

    public string UserLevel { get; set; }

    public string AssignmentCode { get; set; }

    public string Title { get; set; }

    public string Phone { get; set; }

    public string Moblie { get; set; }

    public string EffectiveDate { get; set; }

    public string EmployeeId { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }
}