// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ef8PowerTools.Data.Models
{
    public partial class BridgeEligibilityValidationCheckResult
    {
        public string PatientEnrolled { get; set; }
        public string PatientUnderHealthCareProvider { get; set; }
        public string PatientUSAResident { get; set; }
        public string PatientDiagnosis { get; set; }
        public string PrivateInsurance { get; set; }
        public string GovInsurance { get; set; }
        public string HippaConsent { get; set; }
    }
}
