// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class CoherusGroupsStage
{
    public int Id { get; set; }

    public string GroupId { get; set; }

    public string GroupName { get; set; }

    public string GroupLevel { get; set; }

    public string GroupType { get; set; }

    public string ParentGroupId { get; set; }

    public string BusinessUnitName { get; set; }

    public string BusinessUnitActiveStartDate { get; set; }

    public string BusinessUnitActiveEndDate { get; set; }

    public string SalesTeamName { get; set; }

    public string TerrActiveStartDate { get; set; }

    public string TerrActiveEndDate { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public string FileName { get; set; }
}