// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class ConnectPayerMap
{
    public int ConnectPayerMapId { get; set; }

    public int OfframpClientId { get; set; }

    public string ClientPayerName { get; set; }

    public int? EBvpayerId { get; set; }

    public int? ConnectPayerId { get; set; }

    public string ConnectDefaultPayer { get; set; }

    public bool Active { get; set; }

    public bool Deleted { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }

    public virtual OfframpClient OfframpClient { get; set; }
}