// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class CopayPskwredemption
{
    public int RecordId { get; set; }

    public int ProgramId { get; set; }

    public DateTime Created { get; set; }

    public string Rxnum { get; set; }

    public string DateOfFill { get; set; }

    public string DateWritten { get; set; }

    public string DaySupply { get; set; }

    public string Daw { get; set; }

    public string Ndc { get; set; }

    public string DrugDesc { get; set; }

    public string NewRefillCode { get; set; }

    public string NumberOfRefills { get; set; }

    public string OtherCoverageCode { get; set; }

    public string GroupNum { get; set; }

    public string MemberId { get; set; }

    public string PatientGender { get; set; }

    public string DateProcessed { get; set; }

    public string Nabp { get; set; }

    public string PhmName { get; set; }

    public string PhmAdd1 { get; set; }

    public string PhmAdd2 { get; set; }

    public string PhmCity { get; set; }

    public string PhmState { get; set; }

    public string PhmZip { get; set; }

    public string Npi { get; set; }

    public string PhyName { get; set; }

    public string PhyFn { get; set; }

    public string PhyMi { get; set; }

    public string PhyLn { get; set; }

    public string PhySuffix { get; set; }

    public string PhyProfDesg { get; set; }

    public string Spec1 { get; set; }

    public string Spec2 { get; set; }

    public string PhyAdd1 { get; set; }

    public string PhyAdd2 { get; set; }

    public string PhyCity { get; set; }

    public string PhyState { get; set; }

    public string PhyZip { get; set; }

    public string SubmissionMethod { get; set; }

    public string Quantity { get; set; }

    public string PatientBenefit { get; set; }

    public string PatientCopayBeforeBenefitApplied { get; set; }

    public string PatientOop { get; set; }

    public string PharmacyTransactionFee { get; set; }

    public string FileName { get; set; }

    public int? Linenumber { get; set; }
}