// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class CornerStoneCfsShipment
{
    public int Recordid { get; set; }

    public string HubSrfid { get; set; }

    public string PatientId { get; set; }

    public string DrId { get; set; }

    public string DeaNo { get; set; }

    public string NpiId { get; set; }

    public string Lname { get; set; }

    public string Fname { get; set; }

    public string City { get; set; }

    public string StateCd { get; set; }

    public string Zip { get; set; }

    public string ShipDate { get; set; }

    public string DispNdc { get; set; }

    public string Descr { get; set; }

    public double? DispenseQty { get; set; }

    public double? DispDaysSupply { get; set; }

    public decimal? PertzyeCopayCardAmt { get; set; }

    public decimal? PatientPayPaid { get; set; }

    public string DxCode { get; set; }
}