// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class CrossdbPortalUserAccount
{
    public int AccountId { get; set; }

    public Guid UserId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public string OrderAccountNumber { get; set; }

    public int? CareMetxRecordId { get; set; }

    public string CareMetxRecordType { get; set; }

    public Guid? RoleId { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }

    public bool? Active { get; set; }

    public DateTime? ActiveChangeDate { get; set; }

    public string ActiveChangedBy { get; set; }

    public bool? Deleted { get; set; }

    public Guid? ApplicationId { get; set; }

    public string ExternalUserId { get; set; }

    public string ExternalUserName { get; set; }
}