// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class CrushftpLog
{
    public long LogRowNum { get; set; }

    public long? LogMillis { get; set; }

    public string LogTag { get; set; }

    public string LogData { get; set; }
}