// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ef8PowerTools.Data.Models
{
    public partial class DF_Amicus2_DE_PatientPrescriptionMiglustatResult
    {
        public int PatientPrescriptionClinicalDataMiglustatID { get; set; }
        public int? SRID { get; set; }
        public string DrugName { get; set; }
        public string Dose { get; set; }
        public string Frequency { get; set; }
        public string Dispenseinfusionsuppliesnecesssary { get; set; }
        public string AnaphylaxisOrder { get; set; }
        public string AcquisitionType { get; set; }
        public string RxSignatureDate { get; set; }
        public string Refills { get; set; }
        public string ExpirationDate { get; set; }
        public string ShippingLocation { get; set; }
        public string ShiptoSiteofCare { get; set; }
        public string ShiptoContactPerson { get; set; }
        public string ShiptoAddress1 { get; set; }
        public string ShiptoAddress2 { get; set; }
        public string ShiptoCity { get; set; }
        public string ShiptoState { get; set; }
        public string ShiptoZip { get; set; }
        public string ShiptoPhone { get; set; }
        public string Created { get; set; }
        public string CreatedBy { get; set; }
        public string LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
        public string DeletedYN { get; set; }
        public string ExtractCreatedDate { get; set; }
        public string ExtractUpdatedDate { get; set; }
    }
}
