// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class DfVermedicaEbvtracking
{
    public int TrackingId { get; set; }

    public string ClientPatientId { get; set; }

    public string PatientFirstName { get; set; }

    public string PatientLastName { get; set; }

    public string PatientDob { get; set; }

    public string PatientGender { get; set; }

    public string PatientSsn { get; set; }

    public string PatientZip { get; set; }

    public string MedicareId { get; set; }

    public string Product { get; set; }

    public string CptCode1 { get; set; }

    public string CptCode2 { get; set; }

    public string CptCode3 { get; set; }

    public string CptCode4 { get; set; }

    public string CptCode5 { get; set; }

    public string PrimaryDiagnosis { get; set; }

    public string SecondaryDiagnosis { get; set; }

    public string TertiaryDiagnosis { get; set; }

    public string Pos { get; set; }

    public string ProviderFirstName { get; set; }

    public string ProviderLastName { get; set; }

    public string ProviderTitle { get; set; }

    public string ProviderNpi { get; set; }

    public string ProviderState { get; set; }

    public string ProviderTaxId { get; set; }

    public string PracticeName { get; set; }

    public string PracticeAddress1 { get; set; }

    public string PracticeAddress2 { get; set; }

    public string PracticeCity { get; set; }

    public string PracticeState { get; set; }

    public string PracticeZip { get; set; }

    public string PracticeNpi { get; set; }

    public string PracticeFaxNumber { get; set; }

    public string PracticeContactFname { get; set; }

    public string PracticeContactLname { get; set; }

    public string NoFaxingFlag { get; set; }

    public string Mfg { get; set; }

    public string Policy1policyMemberId { get; set; }

    public string Policy1policyPayerId { get; set; }

    public string Policy1policyPayerName { get; set; }

    public string Policy1policyPatientSubscriber { get; set; }

    public string Policy1subscriberfirstName { get; set; }

    public string Policy1subscriberLastName { get; set; }

    public string Policy1subscriberDob { get; set; }

    public string Policy1subscriberGender { get; set; }

    public string Policy1subscriberMemberId { get; set; }

    public string Policy2policyMemberId { get; set; }

    public string Policy2policyPayerId { get; set; }

    public string Policy2policyPayerName { get; set; }

    public string Policy2policyPatientSubscriber { get; set; }

    public string Policy2subscriberFirstName { get; set; }

    public string Policy2subscriberLastName { get; set; }

    public string Policy2subscriberDob { get; set; }

    public string Policy2subscriberGender { get; set; }

    public string Policy2subscriberMemberId { get; set; }

    public string Policy2mcSuppPlanLetter { get; set; }

    public string Policy3policyMemberId { get; set; }

    public string Policy3policyPayerId { get; set; }

    public string Policy3policyPayerName { get; set; }

    public string Policy3policyPatientSubscriber { get; set; }

    public string Policy3subscriberFirstName { get; set; }

    public string Policy3subscriberLastName { get; set; }

    public string Policy3subscriberDob { get; set; }

    public string Policy3subscriberGender { get; set; }

    public string Policy3subscriberMemberId { get; set; }

    public string InternalReference { get; set; }

    public string CopayCardProgram { get; set; }

    public string AltCoverageReferral { get; set; }

    public string NextScheduledDate { get; set; }

    public string DateOfService { get; set; }

    public string SiteOfficeFax { get; set; }

    public string ResponseMessage { get; set; }

    public string ResponseId { get; set; }

    public string ResponseStatus { get; set; }

    public bool? Processed { get; set; }

    public bool Deleted { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }
}