// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class DocumentOutboundFaxis
{
    public int DocumentOutboundFaxId { get; set; }

    public int DocumentId { get; set; }

    public int ProgramId { get; set; }

    public string FaxTo { get; set; }

    public string FaxNumber { get; set; }

    public DateTime? ProcessedDate { get; set; }

    public string ProcessedBy { get; set; }

    public DateTime? SentDate { get; set; }

    public string FaxStatus { get; set; }

    public string StatusReason { get; set; }

    public DateTime? StatusDate { get; set; }

    public int? FaxJobId { get; set; }

    public string FaxJobXdn { get; set; }
}