// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class DocumentsInboundFaxis
{
    public int DocumentsInboundFaxId { get; set; }

    public int DocumentsFaxQueueId { get; set; }

    public DateTime ReceivedDate { get; set; }

    public string FaxNumber { get; set; }

    public string NumberofPages { get; set; }

    public int DocumentStorageId { get; set; }

    public string DocumentStorageType { get; set; }

    public int? ParentId { get; set; }

    public string Status { get; set; }

    public string ProcessedBy { get; set; }

    public DateTime? ProcessedDate { get; set; }

    public int? DocumentId { get; set; }

    public string ReasonDeleted { get; set; }

    public bool? AssignmentInProgress { get; set; }

    public string TakenBy { get; set; }

    public DateTime? TakenAt { get; set; }

    public string PageRange { get; set; }

    public string FaxTo { get; set; }

    public string FaxBy { get; set; }

    public DateTime? DirectFaxDate { get; set; }

    public int? DirectFaxId { get; set; }

    public string GroupName { get; set; }

    public string GroupPageNumbers { get; set; }

    public string GroupMissingPageNumbers { get; set; }

    public string Priority { get; set; }

    public string OcrExtractStatus { get; set; }

    public virtual DocumentsFaxQueue DocumentsFaxQueue { get; set; }
}