// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class EpsilonCallLog
{
    public int EpsilonCallLogId { get; set; }

    public int ProgramId { get; set; }

    public DateTime CallDate { get; set; }

    public string CallType { get; set; }

    public int Srid { get; set; }

    public string SrsubTypeTrigger { get; set; }

    public string ActivityTypeTrigger { get; set; }

    public string ScreenName { get; set; }

    public string CreatedBy { get; set; }

    public bool Failed { get; set; }

    public string LogMessage { get; set; }

    public string RequestXml { get; set; }

    public string ResponseXml { get; set; }
}