// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class FaxSampleReport
{
    public string Uan { get; set; }

    public string Alias { get; set; }

    public string GroupName { get; set; }

    public string Jobno { get; set; }

    public string Cref { get; set; }

    public string Billcode { get; set; }

    public string StartDate { get; set; }

    public string StartTime { get; set; }

    public string CompleteDate { get; set; }

    public string CompleteTime { get; set; }

    public string Status { get; set; }

    public string To { get; set; }

    public string Dnis { get; set; }

    public string Ani { get; set; }

    public string Subject { get; set; }

    public string FaxPartial { get; set; }

    public string Retries { get; set; }

    public string Pages { get; set; }
}