// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class FieldPortalConfig
{
    public int Id { get; set; }

    public int ProgramId { get; set; }

    public string ManufactureName { get; set; }

    public string ConfigName { get; set; }

    public string ConfigValue { get; set; }

    public bool Active { get; set; }

    public bool Deleted { get; set; }

    public DateTime Created { get; set; }

    public string Createdby { get; set; }

    public string Lastupdated { get; set; }

    public string LastUpdatedBy { get; set; }
}