// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class FundReopenSubscriptionSubscriber
{
    public int FundReopenSubscriptionSubscriberId { get; set; }

    public int SubscriptionId { get; set; }

    public string SubscriberFirstName { get; set; }

    public string SubscriberLastName { get; set; }

    public string SubscriberEmailAddress { get; set; }

    public int SubscriberType { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public virtual FundReopenSubscriptionDetail Subscription { get; set; }
}