// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class FundReopenSubscriptionMedication
{
    public int FundReopenSubscriptionMedicationId { get; set; }

    public int SubscriptionId { get; set; }

    public int DrugId { get; set; }

    public string DrugName { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public bool Deleted { get; set; }

    public virtual FundReopenSubscriptionDetail Subscription { get; set; }
}