// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class HcpservicesApicallLog
{
    public int LogId { get; set; }

    public string Source { get; set; }

    public string ErrorMessage { get; set; }

    public string RequestMethod { get; set; }

    public string RequestUrl { get; set; }

    public string RequestPayload { get; set; }

    public DateTime? RequestCreated { get; set; }

    public string ResponseStatusCode { get; set; }

    public string Response { get; set; }

    public DateTime? ResponseCreated { get; set; }

    public string RequestedBy { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? Created { get; set; }
}