// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class Image
{
    public double Imgid { get; set; }

    public string Imgfilenm { get; set; }

    public byte[] Image1 { get; set; }

    public string DrugName { get; set; }
}