// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class ImportProvider
{
    public int ProviderId { get; set; }

    public string First { get; set; }

    public string Last { get; set; }

    public string Degree { get; set; }

    public string Address1 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public string Phone { get; set; }

    public string AddressName { get; set; }

    public string AddressType { get; set; }

    public string Npi { get; set; }

    public string Dea { get; set; }

    public string AcctAddress1 { get; set; }

    public string AcctAddress2 { get; set; }

    public string AcctCity { get; set; }

    public string AcctState { get; set; }

    public string AcctZip { get; set; }

    public string CleanedPhone { get; set; }

    public string CleanedExt { get; set; }

    public string Address2 { get; set; }
}