// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class LookupInfinitusPayerId
{
    public string PayerName { get; set; }

    public string InfinitusPayerId { get; set; }
}