// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class LtrNotificationMaster
{
    public int NotificationId { get; set; }

    public int ProgramId { get; set; }

    public int? ServiceRequestId { get; set; }

    public int? ApplicationId { get; set; }

    public int? OrganizationId { get; set; }

    public int? MasterStatusId { get; set; }

    public DateTime? ProcessedDate { get; set; }

    public string Message { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public string CreatedSource { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public virtual ICollection<LtrNotificationItem> LtrNotificationItems { get; set; } = new List<LtrNotificationItem>();

    public virtual ICollection<LtrProcessLog> LtrProcessLogs { get; set; } = new List<LtrProcessLog>();
}