// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class MdmpatientSearchResult
{
    public int MdmpatientSearchResultId { get; set; }

    public int? ProgramId { get; set; }

    public int? PatientId { get; set; }

    public string ExternalId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Dob { get; set; }

    public string Email { get; set; }

    public string Gender { get; set; }

    public string Address1 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public string Phone { get; set; }

    public string MatchType { get; set; }

    public string Source { get; set; }

    public DateTime ExecutionDate { get; set; }

    public bool DupCheckOnly { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public virtual ICollection<DuplicatePatientQueue> DuplicatePatientQueues { get; set; } = new List<DuplicatePatientQueue>();

    public virtual ICollection<MdmpatientProcessResult> MdmpatientProcessResults { get; set; } = new List<MdmpatientProcessResult>();
}