// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class MdmSalesAlignment
{
    public string SaleId { get; set; }

    public string TerrId { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public int? ProgramId { get; set; }
}