// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class MedeBvofframpCobblurbRule
{
    public int MedeBvofframpCobblurbRulesId { get; set; }

    public string PayerCategory { get; set; }

    public string PayerType { get; set; }

    public string SecEligibilityStatus { get; set; }

    public string SecCoordinates { get; set; }

    public bool Active { get; set; }

    public bool Deleted { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }

    public string BlurbMessage { get; set; }

    public string AdditionalRule { get; set; }

    public virtual ICollection<MedeBvofframpCobblurbAdditionalRule> MedeBvofframpCobblurbAdditionalRules { get; set; } = new List<MedeBvofframpCobblurbAdditionalRule>();
}