// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class Message
{
    public int MessageId { get; set; }

    public int ProgramId { get; set; }

    public int ThreadId { get; set; }

    public int? OrganizationId { get; set; }

    public int? ProviderId { get; set; }

    public int? PatientId { get; set; }

    public string MessageText { get; set; }

    public Guid SendFromUserId { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public bool IsRead { get; set; }

    public string SenderFirstName { get; set; }

    public string SenderLastName { get; set; }

    public string Source { get; set; }

    public bool? HasAttachment { get; set; }

    public string Reviewed { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual Patient Patient { get; set; }

    public virtual Physician Provider { get; set; }

    public virtual MessageThread Thread { get; set; }
}