// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class MpuAssessmentDetail
{
    public string AssessmentDetailId { get; set; }

    public string AssessmentId { get; set; }

    public string AssessmentQuestionId { get; set; }

    public string AssessmentQuestionScore { get; set; }
}