// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class MpuAssessmentAnswer
{
    public string AssessmentAnswerId { get; set; }

    public string AssessmentQuestionId { get; set; }

    public string AssessmentAnswer { get; set; }

    public string AssessmentAnswerScore { get; set; }

    public string NextQuestionId { get; set; }

    public string DisplayTextControl { get; set; }

    public string DisplayTextControlRequired { get; set; }

    public string ResetOtherOptions { get; set; }

    public string EnableList { get; set; }

    public string DisableList { get; set; }

    public string CreatedUser { get; set; }

    public string CreatedDate { get; set; }

    public string ModifiedUser { get; set; }

    public string ModifiedDate { get; set; }

    public string Active { get; set; }
}