// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class NurseAgencyCoveredCounty
{
    public int NaCoveredCountiesId { get; set; }

    public int NurseAgencyId { get; set; }

    public string CoveredCounty { get; set; }

    public string CoveredCountyState { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public bool Deleted { get; set; }

    public virtual NurseAgency NurseAgency { get; set; }
}