// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class OrganizationNpi
{
    public int OrganizationNpiid { get; set; }

    public int OrganizationId { get; set; }

    public int OrganizationAddressId { get; set; }

    public int ProgramId { get; set; }

    public string Npi { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public string PharmacyNabp { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual OrganizationAddress OrganizationAddress { get; set; }

    public virtual Program Program { get; set; }
}