// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class PanApplicationTokenRole
{
    public int ApplicationTokenId { get; set; }

    public int ApplicationId { get; set; }

    public int ClientId { get; set; }

    public string TokenKey { get; set; }

    public string TokenSecret { get; set; }

    public int RoleId { get; set; }

    public int ProgramId { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public bool Active { get; set; }

    public virtual PanApplication Application { get; set; }

    public virtual PanApplication Client { get; set; }

    public virtual PanApplicationRole Role { get; set; }
}