// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class PatientJourneyDatum
{
    public int Pkid { get; set; }

    public int? ExportId { get; set; }

    public DateTime? TimeStamp { get; set; }

    public int? ProgramId { get; set; }

    public string DrugName { get; set; }

    public string RegionCode { get; set; }

    public string TerritoryCode { get; set; }

    public int? CarecycleId { get; set; }

    public DateTime? CarecycleStartDate { get; set; }

    public int? PatientId { get; set; }

    public string PatientName { get; set; }

    public string PatientInit { get; set; }

    public string Territory { get; set; }

    public string Zip { get; set; }

    public string PatCategory { get; set; }

    public string StartSmntype { get; set; }

    public string PatientStatus { get; set; }

    public string PhysicianName { get; set; }

    public string CoCnurseInit { get; set; }

    public string CoCnurseCurrent { get; set; }

    public string CareCycleState { get; set; }

    public string SmnreferralReceivedDate { get; set; }

    public string SmnreferralReceivedDateNa { get; set; }

    public string Pafreceived { get; set; }

    public string PafreceivedNa { get; set; }

    public string PafreceivedColor { get; set; }

    public string Bicompleted { get; set; }

    public string BicompletedNa { get; set; }

    public string BicompletedColor { get; set; }

    public string CompleteSmnreceived { get; set; }

    public string InitialPriorAuthorization { get; set; }

    public string InitialPriorAuthorizationNa { get; set; }

    public string InitialPriorAuthorizationColor { get; set; }

    public string MaintenancePriorAuthorization { get; set; }

    public string MaintenancePriorAuthorizationNa { get; set; }

    public string MaintenancePriorAuthorizationColor { get; set; }

    public string Painitiated { get; set; }

    public string InitialShipDate { get; set; }

    public string InitialShipDateNa { get; set; }

    public string InitialShipDateColor { get; set; }

    public string NurseAssignmentDate { get; set; }

    public string NurseAssignmentDateNa { get; set; }

    public string NurseAssignmentDateColor { get; set; }

    public string FirstWecomeCallAttempt { get; set; }

    public string FirstWecomeCallAttemptNa { get; set; }

    public string FirstWecomeCallAttemptColor { get; set; }

    public string WelcomeCallCompleted { get; set; }

    public string WelcomeCallCompletedNa { get; set; }

    public string PreInitiationEducationVisit { get; set; }

    public string PreInitiationEducationVisitNa { get; set; }

    public string InitiationVisit { get; set; }

    public string InitiationVisitNa { get; set; }

    public string InitiationVisitColor { get; set; }

    public string Call24hourPostInitiation { get; set; }

    public string Call24hourPostInitiationNa { get; set; }

    public string Call24hourPostInitiationColor { get; set; }

    public string MaintenanceSmnreceived { get; set; }

    public string MaintenanceSmnreceivedNa { get; set; }

    public string MaintenanceSmnreceivedColor { get; set; }

    public string Visit1weekPostinitiation { get; set; }

    public string Visit1weekPostinitiationNa { get; set; }

    public string Visit1weekPostinitiationColor { get; set; }

    public string Call2weekpostinitiationeducation { get; set; }

    public string Call2weekpostinitiationeducationNa { get; set; }

    public string Call2weekpostinitiationeducationColor { get; set; }

    public string CurrentMaintenanceSmnreceived { get; set; }

    public string CurrentMaintenanceSmnreceivedNa { get; set; }

    public string MonthlyFollowUp { get; set; }

    public string MonthlyFollowUpNa { get; set; }

    public string PostInitiationFollowUpVisit { get; set; }

    public string PostInitiationFollowUpVisitNa { get; set; }

    public string LastShipDate { get; set; }

    public string LastShipDateNa { get; set; }

    public string DaysSinceLastFill { get; set; }

    public string SpecialtyPharmacy { get; set; }

    public string CurrentPastartDate { get; set; }

    public string CurrentPastartDateNa { get; set; }

    public string CurrentPacompletedDate { get; set; }

    public string CurrentPacompletedDateNa { get; set; }

    public string CurrentPacompletedDateColor { get; set; }

    public string CreatedBy { get; set; }

    public bool? Over180days { get; set; }

    public string PatientStatusDate { get; set; }

    public string RefillRemaining { get; set; }

    public string MostRecentContactAttempt { get; set; }

    public string MostRecentCompletedContact { get; set; }

    public string CallPostInitiationTitration { get; set; }

    public string CallPostInitiationTitrationNa { get; set; }

    public string CallPostInitiationTitrationColor { get; set; }

    public string TitrationFormFaxedtoHcp { get; set; }

    public string TitrationFormFaxedtoHcpna { get; set; }
}