// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class PatientDupeSearchResponse
{
    public int PatientDupeSearchResponseId { get; set; }

    public int? EntityDupeSearchRequestId { get; set; }

    public int? PatientId { get; set; }

    public string ExternalId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime? Dob { get; set; }

    public string Ssn { get; set; }

    public string Zip { get; set; }

    public string MatchScore { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string UpdatedBy { get; set; }
}