// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class PortalStagingRegistration
{
    public int RegistratoinRecordId { get; set; }

    public int? ProgramId { get; set; }

    public string AccountType { get; set; }

    public string PracticeName { get; set; }

    public string Npi { get; set; }

    public string ContactType { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string Email { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string AddressType { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public string Phone { get; set; }

    public string PhoneType { get; set; }

    public string Fax { get; set; }

    public string Facility { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public string StagingStatus { get; set; }

    public DateTime? ProcessDate { get; set; }

    public string ProcessedBy { get; set; }

    public int? HubRecordId { get; set; }

    public string Reason { get; set; }

    public bool? ProcessingInProgress { get; set; }

    public string TakenBy { get; set; }

    public DateTime? TakenAt { get; set; }

    public string TaxId { get; set; }

    public int? AccountId { get; set; }

    public string MedicareId { get; set; }

    public string Speciality { get; set; }

    public string Phone2 { get; set; }

    public string PhoneType2 { get; set; }

    public bool? AuthorizeContact { get; set; }

    public string Dea { get; set; }

    public string Degree { get; set; }

    public string MiddleName { get; set; }

    public bool? PotentialDuplicate { get; set; }

    public string IndividualNpi { get; set; }

    public int? HubRecordOrgId { get; set; }

    public string PracticeUrl { get; set; }

    public string PhoneExtension { get; set; }

    public string UserType { get; set; }

    public Guid? UserId { get; set; }

    public int? RegistrationRecordAddressId { get; set; }

    public int? OrganizationAddressId { get; set; }

    public string BestTimeToContact { get; set; }

    public string Phone2Extension { get; set; }

    public string PreferredCommunicationMethod { get; set; }

    public string PortalType { get; set; }

    public string Ncpdp { get; set; }

    public string OptOut { get; set; }

    public string Fax2 { get; set; }

    public string ContactCategory { get; set; }

    public string BillingPreference { get; set; }

    public string SiteOfService { get; set; }

    public string IndividualTaxId { get; set; }

    public string StateLicenseNumber { get; set; }

    public string LicensingState { get; set; }

    public string Suffix { get; set; }

    public bool TermsAndConditionsAcknowledgement { get; set; }

    public bool Baaacknowledgement { get; set; }

    public bool BaalanguageAcknowledgement { get; set; }

    public string BaasignatureText { get; set; }

    public DateOnly? BaasignatureDate { get; set; }

    public string RegisteredFromIpaddress { get; set; }

    public int? BaadocumentListId { get; set; }

    public string Ptan { get; set; }

    public string PrescriberEmail { get; set; }

    public int? BifileDocumentId { get; set; }

    public int? TermsOfUserFileDocumentId { get; set; }

    public string PortalRegistrationType { get; set; }

    public virtual ICollection<PortalStagingRegistrationAddress> PortalStagingRegistrationAddresses { get; set; } = new List<PortalStagingRegistrationAddress>();

    public virtual ICollection<PortalStagingRegistrationEntity> PortalStagingRegistrationEntities { get; set; } = new List<PortalStagingRegistrationEntity>();
}