// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class PortalStagingTblFile
{
    public int IFileId { get; set; }

    public string FileName { get; set; }

    public long? FileSize { get; set; }

    public byte[] FileData { get; set; }

    public string ContentType { get; set; }

    public int? PortalStagingHcpSrrequestId { get; set; }

    public DateTime? CreatedTime { get; set; }

    public virtual PortalStagingHcpSr PortalStagingHcpSrrequest { get; set; }
}