// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class PortalRosterStage
{
    public int Id { get; set; }

    public int? ProgramId { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Role { get; set; }

    public string AssignmentCode { get; set; }

    public string AssignmentName { get; set; }

    public string Title { get; set; }

    public string Phone { get; set; }

    public DateTime? HireDate { get; set; }

    public string SalesDivision { get; set; }

    public string FileName { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public string Gender { get; set; }

    public int? LineNumber { get; set; }

    public string InternalPhone { get; set; }

    public string EmployeeId { get; set; }

    public string TerritoryId { get; set; }

    public string TerritoryName { get; set; }

    public string DistrictId { get; set; }

    public string DistrictName { get; set; }

    public string RegionId { get; set; }

    public string RegionName { get; set; }

    public string CustomData1 { get; set; }

    public string CustomData2 { get; set; }

    public string CustomData3 { get; set; }
}