// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class PortalSoc
{
    public int PortalSocid { get; set; }

    public int? ProgramId { get; set; }

    public string SocId { get; set; }

    public string SocAccountName { get; set; }

    public string TerritoryId { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public DateTime? Created { get; set; }

    public string Createby { get; set; }

    public DateTime? Lastupdated { get; set; }

    public string Lastupdatedby { get; set; }

    public bool? Deleted { get; set; }

    public bool? Active { get; set; }
}