// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class PortalFunction
{
    public int PortalFunctionId { get; set; }

    public int ProgramPortalTypeId { get; set; }

    public int PortalFunctionListId { get; set; }

    public string Comments { get; set; }

    public int? SortOrder { get; set; }

    public bool Active { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }

    public DateTime? ActivatedDate { get; set; }

    public bool Deleted { get; set; }

    public virtual PortalFunctionList PortalFunctionList { get; set; }

    public virtual ProgramPortalType ProgramPortalType { get; set; }
}