// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class PortalSalesForceProgram
{
    public int SalesForceProgramId { get; set; }

    public int ProgramId { get; set; }

    public string SalesForce { get; set; }

    public string FunctionLabel { get; set; }

    public string Description { get; set; }

    public string Therapy { get; set; }

    public bool? Active { get; set; }

    public bool? Deleted { get; set; }

    public DateTime? EffectiveDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }
}