// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class Program
{
    public int ProgramId { get; set; }

    public string ProgramName { get; set; }

    public int ManufacturerId { get; set; }

    public string ManufacturerName { get; set; }

    public int MdmprogramId { get; set; }

    public bool Active { get; set; }

    public DateOnly? ActiveDate { get; set; }

    public int? MaxCopayAmount { get; set; }

    public string CopayType { get; set; }

    public int? CopayPeriodDays { get; set; }

    public int? SharedRecordProgramId { get; set; }

    public bool? DefaultProgram { get; set; }

    public string ManufacturerApplicationName { get; set; }

    public string LayoutType { get; set; }

    public string ManuPortalConfigDb { get; set; }

    public bool? DisplayScientificDrugName { get; set; }

    public string CopayGroupId { get; set; }

    public string HcpapplicationName { get; set; }

    public string ClientApplicationName { get; set; }

    public virtual ICollection<Contact> Contacts { get; set; } = new List<Contact>();

    public virtual ICollection<DashboardPanelProgram> DashboardPanelPrograms { get; set; } = new List<DashboardPanelProgram>();

    public virtual ICollection<DashboardPanelUserSetting> DashboardPanelUserSettings { get; set; } = new List<DashboardPanelUserSetting>();

    public virtual ICollection<DataConfiguration> DataConfigurations { get; set; } = new List<DataConfiguration>();

    public virtual ICollection<DocumentsFaxQueue> DocumentsFaxQueues { get; set; } = new List<DocumentsFaxQueue>();

    public virtual ICollection<EServicesProgramConfig> EServicesProgramConfigs { get; set; } = new List<EServicesProgramConfig>();

    public virtual ICollection<FeedbackConfiguration> FeedbackConfigurations { get; set; } = new List<FeedbackConfiguration>();

    public virtual ICollection<OrganizationAddress> OrganizationAddresses { get; set; } = new List<OrganizationAddress>();

    public virtual ICollection<OrganizationNpi> OrganizationNpis { get; set; } = new List<OrganizationNpi>();

    public virtual ICollection<OrganizationPhoneNumber> OrganizationPhoneNumbers { get; set; } = new List<OrganizationPhoneNumber>();

    public virtual ICollection<OrganizationTaxId> OrganizationTaxIds { get; set; } = new List<OrganizationTaxId>();

    public virtual ICollection<Organization> Organizations { get; set; } = new List<Organization>();

    public virtual ICollection<PatientAddress> PatientAddresses { get; set; } = new List<PatientAddress>();

    public virtual ICollection<PatientPhoneNumber> PatientPhoneNumbers { get; set; } = new List<PatientPhoneNumber>();

    public virtual ICollection<PatientStatusProgramList> PatientStatusProgramLists { get; set; } = new List<PatientStatusProgramList>();

    public virtual ICollection<PhysicianPhoneNumber> PhysicianPhoneNumbers { get; set; } = new List<PhysicianPhoneNumber>();

    public virtual ICollection<Physician> Physicians { get; set; } = new List<Physician>();

    public virtual ICollection<ProgramUrl> ProgramUrls { get; set; } = new List<ProgramUrl>();

    public virtual ICollection<ProgramVendor> ProgramVendors { get; set; } = new List<ProgramVendor>();

    public virtual ICollection<ReportProgram> ReportPrograms { get; set; } = new List<ReportProgram>();

    public virtual ICollection<RxAdminDose> RxAdminDoses { get; set; } = new List<RxAdminDose>();

    public virtual ICollection<ServiceRequest> ServiceRequests { get; set; } = new List<ServiceRequest>();

    public virtual ICollection<SrOrderDetail> SrOrderDetails { get; set; } = new List<SrOrderDetail>();

    public virtual ICollection<SrPappaymentSchedule> SrPappaymentSchedules { get; set; } = new List<SrPappaymentSchedule>();

    public virtual ICollection<SrPappayment> SrPappayments { get; set; } = new List<SrPappayment>();

    public virtual ICollection<SrPapscheduledPayment> SrPapscheduledPayments { get; set; } = new List<SrPapscheduledPayment>();

    public virtual ICollection<SrTriage> SrTriages { get; set; } = new List<SrTriage>();

    public virtual ICollection<SrhubStatusSrtypeList> SrhubStatusSrtypeLists { get; set; } = new List<SrhubStatusSrtypeList>();

    public virtual ICollection<UserAccessFunctionList> UserAccessFunctionLists { get; set; } = new List<UserAccessFunctionList>();

    public virtual ICollection<UserProgram> UserPrograms { get; set; } = new List<UserProgram>();

    public virtual ICollection<UserRoleDefault> UserRoleDefaults { get; set; } = new List<UserRoleDefault>();

    public virtual ICollection<UserRoleList> UserRoleLists { get; set; } = new List<UserRoleList>();
}