// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class ProgramCopayCardId
{
    public int ProgramCopayCardId1 { get; set; }

    public int? ProgramId { get; set; }

    public string DrugName { get; set; }

    public string GroupId { get; set; }

    public int? CopayCardIdBegin { get; set; }

    public int? CopayCardIdEnd { get; set; }

    public int NextCopayCardId { get; set; }

    public DateTime? LastUpdated { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public string ExternalId { get; set; }

    public string Bin { get; set; }

    public string Pcn { get; set; }

    public string GroupNum { get; set; }
}