// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class ReportProgram
{
    public int ReportProgramsId { get; set; }

    public int ReportListId { get; set; }

    public int ProgramId { get; set; }

    public double? SortOrder { get; set; }

    public bool Active { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public virtual Program Program { get; set; }

    public virtual ICollection<ReportActivityHistory> ReportActivityHistories { get; set; } = new List<ReportActivityHistory>();

    public virtual ReportList ReportList { get; set; }
}