// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class Rimguij2UnqDrugJrnl
{
    public double Imguniqid { get; set; }

    public double Imgstrtdt { get; set; }

    public double? Imgstopdt { get; set; }

    public double? Imgid { get; set; }
}