// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class RuleTriggerCondition
{
    public int RuleTriggerConditionId { get; set; }

    public int ProgramId { get; set; }

    public string RuleName { get; set; }

    public string SrTypeShortDesc { get; set; }

    public string SrStatus { get; set; }

    public string SrResolution { get; set; }

    public string SrActivity { get; set; }

    public string SrProcessDate { get; set; }

    public string SrTask { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public string SrSubtype { get; set; }

    public string DrugName { get; set; }

    public bool? RequireCareCycle { get; set; }

    public string ConditionParameters { get; set; }

    public string ProcessName { get; set; }

    /// <summary>
    /// Example: {&quot;RunByWindowsTaskScheduler&quot;:&quot;false&quot;,&quot;Month&quot;:&quot;May,June,July&quot;,&quot;Date01,02,11,30&quot;:&quot;&quot;,&quot;Day&quot;:&quot;Monday,tuesday,Friday,saturday&quot;,&quot;Hour&quot;:&quot;11,09,10&quot;,&quot;Minute&quot;:&quot;11,00,23&quot;}
    /// Details: Month,Day should be full name(case insensitive). Date, Hour, Minute are in ## format. Hour are in 24 hour date format. When RunByWindowsTaskScheduler is true all other paratmeter values are ignored and Job will be executed as per the Windows Task scheduler timing. 
    /// </summary>
    public string TaskRunFrequency { get; set; }

    public virtual ICollection<RuleTriggerAction> RuleTriggerActions { get; set; } = new List<RuleTriggerAction>();
}