// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class SecureCommunicationDocument
{
    public int SecureCommunicationDocumentId { get; set; }

    public int SecureCommunicationId { get; set; }

    public int? FileStorageId { get; set; }

    public int? TemplateId { get; set; }

    public bool SigRequired { get; set; }

    public string SigStatus { get; set; }

    public string Checksum { get; set; }

    public DateTime Created { get; set; }
}