// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class SmsTemplate
{
    public int SmsTemplateId { get; set; }

    public int ProgramId { get; set; }

    public string Smscategory { get; set; }

    public string Smstemplate1 { get; set; }

    public string SrTypeShortDesc { get; set; }

    public int? SrTypeListId { get; set; }

    public bool Active { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }
}