// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class SoapauditLog
{
    public int LogId { get; set; }

    public string ServiceName { get; set; }

    public string MethodName { get; set; }

    public string Url { get; set; }

    public string IpAddress { get; set; }

    public string XmlRequest { get; set; }

    public string XmlResponse { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }
}