// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class SrCopayClaim
{
    public int SrCopayClaimId { get; set; }

    public int ProgramId { get; set; }

    public int Srid { get; set; }

    public int? PatientId { get; set; }

    public int? OrganizationId { get; set; }

    public int? PhysicianId { get; set; }

    public string ExternalId { get; set; }

    public string ConfirmationNumber { get; set; }

    public string PracticeExternalId { get; set; }

    public string PrescriberExternalId { get; set; }

    public string PatientExternalId { get; set; }

    public string Status { get; set; }

    public string TrackingNumber { get; set; }

    public string GroupNumber { get; set; }

    public string CopayCardNumber { get; set; }

    public DateTime? ApiDateCreated { get; set; }

    public DateTime? ApiDateModified { get; set; }

    public DateTime? PrescriptionFillDate { get; set; }

    public string PrescriptionNumber { get; set; }

    public decimal? SubmittedCopay { get; set; }

    public decimal? BenefitAmount { get; set; }

    public string ReimbursementType { get; set; }

    public string ProductNdc { get; set; }

    public bool Deleted { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }

    public string ClaimType { get; set; }

    public string Dose { get; set; }

    public string DaysSupplied { get; set; }

    public bool? EobonFile { get; set; }

    public DateTime? StatusDate { get; set; }

    public decimal? ResponseCopayAmount { get; set; }

    public DateOnly? PaidDate { get; set; }

    public string ResponseClaimNumber { get; set; }

    public string ResponseAdjustedClaimNumber { get; set; }

    public string ResponseSubmissionMethod { get; set; }

    public string ResponseNumberofBenefits { get; set; }

    public string ResponseApsindicator { get; set; }

    public string ResponseDispensingFeePaid { get; set; }

    public string ResponseTraditionalCardSpend { get; set; }

    public string ResponseUsualandCustomaryAmount { get; set; }

    public string ResponseDateWritten { get; set; }

    public string ResponseDateofFill { get; set; }

    public string ResponseReceivedDate { get; set; }

    public string ResponseRxNumber { get; set; }

    public string ResponseRxOriginCode { get; set; }

    public string ResponseNewRefillCode { get; set; }

    public string ResponseNumberofRefills { get; set; }

    public string ResponseDawcode { get; set; }

    public string ResponseOtherCoverage { get; set; }

    public string ResponseBasisofReimbursement { get; set; }

    public string ResponseNdc { get; set; }

    public string ResponseDrugName { get; set; }

    public string ResponseDrugDosageForm { get; set; }

    public string ResponseDrugStrength { get; set; }

    public string ResponsePaidQuantity { get; set; }

    public string ResponseDaysSupply { get; set; }

    public string ResponseOrganizationNpi { get; set; }

    public string ResponsePharmacyNabpnumber { get; set; }

    public string ResponsePharmacyName { get; set; }

    public string ResponsePharmacyGroupCode { get; set; }

    public string ResponseMailOrderIndicator { get; set; }

    public string ResponseDea { get; set; }

    public string ResponseNpi { get; set; }

    public string ResponseImsid { get; set; }

    public string ResponsePrescriberFirstName { get; set; }

    public string ResponsePdrp { get; set; }

    public string ResponseIqviatransactionId { get; set; }

    public string ResponseEobFlag { get; set; }
}