// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class SrMedOffRampDatum
{
    public int SrMedOffRampDataId { get; set; }

    public int SrOffRampId { get; set; }

    public string ManualBvRequestId { get; set; }

    public string MedEbvResponseId { get; set; }

    public string MedEbvResponseStatus { get; set; }

    public string MedEbvResponseTypeCode { get; set; }

    public string MedEbvResponseTypeMessage { get; set; }

    public int? CaseId { get; set; }

    public string ExternalCaseId1 { get; set; }

    public string ExternalCaseId2 { get; set; }

    public string ExternalCaseId3 { get; set; }

    public int? PatientId { get; set; }

    public string ExternalPatientId1 { get; set; }

    public string ExternalPatientId2 { get; set; }

    public string ExternalPatientId3 { get; set; }

    public string PatientFirstName { get; set; }

    public string PatientMiddleName { get; set; }

    public string PatientLastName { get; set; }

    public string PatientPrefix { get; set; }

    public string PatientSuffix { get; set; }

    public string PatientTitle { get; set; }

    public DateTime? PatientDob { get; set; }

    public string PatientGender { get; set; }

    public string PatientSsn { get; set; }

    public string PatientAddressLine1 { get; set; }

    public string PatientAddressLine2 { get; set; }

    public string PatientAddressLine3 { get; set; }

    public string PatientCity { get; set; }

    public string PatientState { get; set; }

    public string PatientZipCode { get; set; }

    public string PatientCountry { get; set; }

    public string PatientEmail { get; set; }

    public string PatientMedicareId { get; set; }

    public string PatientSubscriberId { get; set; }

    public string ProviderId { get; set; }

    public string ExternalProviderId1 { get; set; }

    public string ExternalProviderId2 { get; set; }

    public string ExternalProviderId3 { get; set; }

    public string ProviderFirstName { get; set; }

    public string ProviderMiddleName { get; set; }

    public string ProviderLastName { get; set; }

    public string ProviderPrefix { get; set; }

    public string ProviderSuffix { get; set; }

    public string ProviderTitle { get; set; }

    public string ProviderNpi { get; set; }

    public string ProviderTexId { get; set; }

    public string ProviderSpecialty { get; set; }

    public string ProviderEmail { get; set; }

    public int? ProviderPracticeId { get; set; }

    public string ProviderExternalPracticeId1 { get; set; }

    public string ProviderExternalPracticeId2 { get; set; }

    public string ProviderExternalPracticeId3 { get; set; }

    public string ProviderPracticeName { get; set; }

    public string ProviderPracticeLegalName { get; set; }

    public string ProviderPracticeNpi { get; set; }

    public string ProviderPracticeAddressLine1 { get; set; }

    public string ProviderPracticeAddressLine2 { get; set; }

    public string ProviderPracticeAddressLine3 { get; set; }

    public string ProviderPracticeCity { get; set; }

    public string ProviderPracticeState { get; set; }

    public string ProviderPracticeZipCode { get; set; }

    public string ProviderPracticeCountry { get; set; }

    public string ProviderPracticeEmail { get; set; }

    public string ProviderPracticeWebsite { get; set; }

    public string ProviderPracticeFirstName { get; set; }

    public string ProviderPracticeMiddleName { get; set; }

    public string ProviderPracticeLastName { get; set; }

    public string ProviderPracticePrefix { get; set; }

    public string ProviderPracticeSuffix { get; set; }

    public string ProviderPracticeTitle { get; set; }

    public string ProviderPracticePlaceOfService { get; set; }

    public int? ProviderPracticePracticeOrganizationId { get; set; }

    public string ProviderPracticeExternalOrganizationId1 { get; set; }

    public string ProviderPracticeExternalOrganizationId2 { get; set; }

    public string ProviderPracticeExternalOrganizationId3 { get; set; }

    public string ProviderPracticeExternalOrganizationName { get; set; }

    public string ProviderPracticeExternalOrganizationLegalName { get; set; }

    public string ProviderPracticeExternalOrganizationNpi { get; set; }

    public string ProviderPracticeExternalOrganizationTaxId { get; set; }

    public string ProviderPracticeOrganizationAddressLine1 { get; set; }

    public string ProviderPracticeOrganizationAddressLine2 { get; set; }

    public string ProviderPracticeOrganizationAddressLine3 { get; set; }

    public string ProviderPracticeOrganizationCity { get; set; }

    public string ProviderPracticeOrganizationState { get; set; }

    public string ProviderPracticeOrganizationZipCode { get; set; }

    public string ProviderPracticeOrganizationCountry { get; set; }

    public string ProviderPracticeOrganizationEmail { get; set; }

    public string ProviderPracticeOrganizationWebsite { get; set; }

    public int? PracticeId { get; set; }

    public string ExternalPracticeId1 { get; set; }

    public string ExternalPracticeId2 { get; set; }

    public string ExternalPracticeId3 { get; set; }

    public string PracticeName { get; set; }

    public string PracticeLegalName { get; set; }

    public string PracticeNpi { get; set; }

    public string PracticeAddressLine1 { get; set; }

    public string PracticeAddressLine2 { get; set; }

    public string PracticeAddressLine3 { get; set; }

    public string PracticeCity { get; set; }

    public string PracticeState { get; set; }

    public string PracticeZipCode { get; set; }

    public string PracticeCountry { get; set; }

    public string PracticeEmail { get; set; }

    public string PracticeWebsite { get; set; }

    public string PracticeFirstName { get; set; }

    public string PracticeMiddleName { get; set; }

    public string PracticeLastName { get; set; }

    public string PracticePrefix { get; set; }

    public string PracticeSuffix { get; set; }

    public string PracticeTitle { get; set; }

    public string PracticePlaceOfService { get; set; }

    public int? PracticePracticeOrganizationId { get; set; }

    public string PracticeExternalOrganizationId1 { get; set; }

    public string PracticeExternalOrganizationId2 { get; set; }

    public string PracticeExternalOrganizationId3 { get; set; }

    public string PracticeOrganizationName { get; set; }

    public string PracticeOrganizationLegalName { get; set; }

    public string PracticeOrganizationNpi { get; set; }

    public string PracticeOrganizationTaxId { get; set; }

    public string PracticeOrganizationAddressLine1 { get; set; }

    public string PracticeOrganizationAddressLine2 { get; set; }

    public string PracticeOrganizationAddressLine3 { get; set; }

    public string PracticeOrganizationCity { get; set; }

    public string PracticeOrganizationState { get; set; }

    public string PracticeOrganizationZipCode { get; set; }

    public string PracticeOrganizationCountry { get; set; }

    public string PracticeOrganizationEmail { get; set; }

    public string PracticeOrganizationWebsite { get; set; }

    public string MedicationProductName { get; set; }

    public string MedicationNdc { get; set; }

    public string MedicationDaysSupply { get; set; }

    public string MedicationQuantity { get; set; }

    public string MedicationJcode { get; set; }

    public string MedicationManufactureName { get; set; }

    public bool? CopayProgramReferral { get; set; }

    public bool? AlternateCoverageReferral { get; set; }

    public DateTime? NextScheduledDate { get; set; }

    public DateTime? DateOfService { get; set; }

    public string RequestingPartyDetailsApplicationName { get; set; }

    public string RequestingPartyDetailsUserName { get; set; }

    public string RequestingPartyDetailsFirstName { get; set; }

    public string RequestingPartyDetailsLastName { get; set; }

    public string RequestingPartyDetailsEmail { get; set; }

    public string RequestingPartyDetailsPhone { get; set; }

    public string RequestingPartyDetailsPhoneType { get; set; }

    public string RequestingPartyDetailsFax { get; set; }

    public string CobSummarycoordinatedPlanBenefits { get; set; }

    public string CobSummaryDeductibleRemaining { get; set; }

    public string CobSummaryProductAmount { get; set; }

    public string CobSummaryOfficeVisitAmount { get; set; }

    public string CobSummaryAdminAmount { get; set; }

    public string CobSummarymedicareSupplementLetter { get; set; }

    public bool? OtherCoverageAvailable { get; set; }

    public DateTime? OtherCoverageEffectiveDate { get; set; }

    public string OtherCoverageMemberId { get; set; }

    public string OtherCoverageName { get; set; }

    public string OtherCoverageResultBenefitVerificationTransactionId { get; set; }

    public DateTime? OtherCoverageResultbenefitVerificationTransactionDate { get; set; }

    public string PolicyHighLevelInfoEligibilityStatus { get; set; }

    public DateTime? PolicyHighLevelInfoEffectiveDate { get; set; }

    public DateTime? PolicyHighLevelInfoEndDate { get; set; }

    public string PolicyHighLevelInfoPayerName { get; set; }

    public string PolicyHighLevelInfoPayerType { get; set; }

    public string PolicyHighLevelInfoPlanName { get; set; }

    public string PolicyHighLevelInfoPlanType { get; set; }

    public string PolicyHighLevelInfoGroupNumber { get; set; }

    public string PolicyHighLevelInfoGroupName { get; set; }

    public string OfficeVisitDetailsStatus { get; set; }

    public string OfficeVisitDetailsDeductibleApplies { get; set; }

    public string OfficeVisitDetailsCopayApplies { get; set; }

    public string OfficeVisitDetailsCoInsApplies { get; set; }

    public string OfficeVisitDetailsOopMaxApplies { get; set; }

    public string OfficeVisitDetailsPcpCopayAmount { get; set; }

    public string OfficeVisitDetailsSpecialistCopayAmount { get; set; }

    public string OfficeVisitDetailsCoInsuranceAmount { get; set; }

    public string ProductStatusDetailsStatus { get; set; }

    public string ProductStatusDetailsDeductibleApplies { get; set; }

    public string ProductStatusDetailsCopayApplies { get; set; }

    public string ProductStatusDetailsCoInsApplies { get; set; }

    public string ProductStatusDetailsOopMaxApplies { get; set; }

    public string ProductStatusDetailsPcpCopayAmount { get; set; }

    public string ProductStatusDetailsSpecialistCopayAmount { get; set; }

    public string ProductStatusDetailscoInsuranceAmount { get; set; }

    public string AccumulatorDetailsDeductibleIndividualAmount { get; set; }

    public string AccumulatorDetailsDeductibleIndividualAmountMet { get; set; }

    public string AccumulatorDetailsDeductibleFamilyAmount { get; set; }

    public string AccumulatorDetailsdseductibleFamilyAmountMet { get; set; }

    public string AccumulatorDetailsOopMaxIndividualAmount { get; set; }

    public string AccumulatorDetailsOopMaxIndividualAmountMet { get; set; }

    public string AccumulatorDetailsOopMaxFamilyAmount { get; set; }

    public string AccumulatorDetailsOopMaxFamilyAmountMet { get; set; }

    public string DrugRequirementspriorAuthorizationRequired { get; set; }

    public string DrugRequirementsisPriorAuthorizationOnFile { get; set; }

    public DateTime? DrugRequirementsPriorAuthorizationEffectiveDate { get; set; }

    public DateTime? DrugRequirementsPriorAuthorizationEndDate { get; set; }

    public string DrugRequirementsPriorTherapyRequired { get; set; }

    public string DrugRequirementsTherapyRestrictionNotes { get; set; }

    public string DrugRequirementsBuyBillPermitted { get; set; }

    public string DrugRequirementsPredeterminationRequired { get; set; }

    public string DrugRequirementsSpecialtyPharmacyRequired { get; set; }

    public string DrugRequirementsSpecialtyPharmacyAvailable { get; set; }

    public string DrugRequirementsSpecialtyPharmacyName { get; set; }

    public string OtherCoverageResultGovernmentPolicyType { get; set; }

    public int? ProgramId { get; set; }

    public string OtherCoverageResultGovernmentPlanDetected { get; set; }

    public string OtherCoverageResultPolicyMessageId { get; set; }

    public string OtherCoverageResultMedicalPolicy { get; set; }

    public string ResponseDataElectronicBenefitVerificationReport { get; set; }

    public string ResponseDataelElectronicBenefitVerificationReportType { get; set; }

    public string DataserviceRequested { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }

    public string PolicyHighLevelInfoPayerId { get; set; }

    public string ManualBvResponseId { get; set; }

    public string TransactionRequestId { get; set; }

    public string TransactionResponseId { get; set; }

    public string MedEbvOffRampStatus { get; set; }

    public string OtherCoverageResultPolicyMessageContent { get; set; }

    public string Message { get; set; }

    public bool? Result { get; set; }

    public string DrugRequirementsPredeterminationAvailable { get; set; }

    public string PracticePhoneNumber { get; set; }

    public string PracticePhoneExtension { get; set; }

    public string PracticePhoneType { get; set; }

    public string PracticeFaxNumber { get; set; }

    public string PracticeFaxType { get; set; }

    public bool? PracticeFaxDoNotFax { get; set; }

    public string DrugRequirementsPriorAuthorizationChannel { get; set; }

    public string DrugRequirementsPriorAuthorizationNumber { get; set; }

    public string MedEbvResponseTypeCodeFinal { get; set; }

    public string EscalationReason { get; set; }

    public string SecondaryCoordinateBenefits { get; set; }

    public string SecondaryCoverPartBdeductible { get; set; }

    public string SecondaryfollowMedicareguidelines { get; set; }

    public string SecondaryCopayOopmax { get; set; }

    public string SecondaryOfficeVisitCopayApply { get; set; }

    public string CallingTransactionId { get; set; }

    public string CallingTransactionType { get; set; }

    public string OutcomeKey { get; set; }

    public string OutcomeKeyDescription { get; set; }

    public string NonDuplicationCoverage { get; set; }

    public virtual ICollection<SrMedOffRampDataCptCode> SrMedOffRampDataCptCodes { get; set; } = new List<SrMedOffRampDataCptCode>();

    public virtual ICollection<SrMedOffRampDataDiagnosis> SrMedOffRampDataDiagnoses { get; set; } = new List<SrMedOffRampDataDiagnosis>();

    public virtual ICollection<SrMedOffRampDataPolicy> SrMedOffRampDataPolicies { get; set; } = new List<SrMedOffRampDataPolicy>();

    public virtual ICollection<SrMedOffRampDataRequestPolicy> SrMedOffRampDataRequestPolicies { get; set; } = new List<SrMedOffRampDataRequestPolicy>();

    public virtual SrOffRamp SrOffRamp { get; set; }
}