// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class SrNoteHistory
{
    public int SrNoteHistoryId { get; set; }

    public int SrNoteId { get; set; }

    public int ServiceRequestId { get; set; }

    public int ProgramId { get; set; }

    public string Subject { get; set; }

    public string NoteText { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? NoteDate { get; set; }

    public virtual ServiceRequest ServiceRequest { get; set; }

    public virtual SrNote SrNote { get; set; }
}