// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class SrSubTypeSubTyleList
{
    public int? ServiceRequestId { get; set; }

    public string SrTypeShortDesc { get; set; }

    public string SrSubTypeFullDesc { get; set; }

    public int? SrTypeListId { get; set; }

    public int? SrSubTypeListId { get; set; }
}