// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class SrTypeList
{
    public int SrTypeListId { get; set; }

    public short ProgramId { get; set; }

    public string SrTypeShortDesc { get; set; }

    public string SrTypeFullDesc { get; set; }

    public decimal? SortOrder { get; set; }

    public bool Active { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }

    public bool? Deleted { get; set; }

    public bool? ShowTriage { get; set; }

    public bool? CanSelectMultipleSubTypes { get; set; }

    public bool? TriagewithoutRule { get; set; }

    public bool? EnablePatientContactOfSr { get; set; }

    public bool? RequireSrpatient { get; set; }

    public bool? RequireSrphysician { get; set; }

    public bool? RequireSrorganization { get; set; }

    public string RequirePatientConsentDrug { get; set; }

    public string RequireDrug { get; set; }

    public bool? TriageWithoutDocument { get; set; }

    public bool? TriageWithoutBi { get; set; }

    public bool? CreateFromCopyOnly { get; set; }

    public bool? ShowFaqs { get; set; }

    public bool? AllowSrtypeChange { get; set; }

    public bool? RequireCarecycleOpenToSave { get; set; }

    public bool? AllowAutoCreateOnly { get; set; }

    public bool? RequireProviderBaa { get; set; }

    public bool? HideBaabannerSrtype { get; set; }

    public string Category { get; set; }

    public bool? NotAllowSelect { get; set; }

    public virtual ICollection<DataConfiguration> DataConfigurations { get; set; } = new List<DataConfiguration>();

    public virtual ICollection<FeedbackConfiguration> FeedbackConfigurations { get; set; } = new List<FeedbackConfiguration>();

    public virtual ICollection<ServiceRequest> ServiceRequests { get; set; } = new List<ServiceRequest>();

    public virtual ICollection<SrTypeActivity> SrTypeActivities { get; set; } = new List<SrTypeActivity>();

    public virtual ICollection<SrTypeConfig> SrTypeConfigs { get; set; } = new List<SrTypeConfig>();
}