// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class SubscriptionHistory
{
    public int SubscriptionHistoryId { get; set; }

    public int SubscriptionId { get; set; }

    public bool Exclude { get; set; }

    public string RequestedBy { get; set; }

    public string Source { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public int ProgramId { get; set; }

    public virtual FundReopenSubscriptionDetail Subscription { get; set; }
}