// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ef8PowerTools.Data.Models
{
    public partial class TakedaHSCPortal_DNBiDetailResult
    {
        public int? SRID { get; set; }
        public int? BIID { get; set; }
        public DateTime? created { get; set; }
        public string createdby { get; set; }
        public int? BenefitHistoryFieldListID { get; set; }
        public string BenefitHistoryFieldValue { get; set; }
        public string FieldName { get; set; }
        public int? SortOrder { get; set; }
    }
}
