// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ef8PowerTools.Data.Models
{
    public partial class TakedaHSCPortal_DNSOCDetailsResult
    {
        public int Portal_SOCID { get; set; }
        public int? ProgramID { get; set; }
        public string SOC_ID { get; set; }
        public string SOC { get; set; }
        public string Territory_ID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
    }
}
