// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ef8PowerTools.Data.Models
{
    public partial class TakedaHSCPortal_GetPatientSRHistoryResult
    {
        public int ServiceRequestID { get; set; }
        public DateTime? StartDate { get; set; }
        public string SRType { get; set; }
        public string SRStatus { get; set; }
        public string SRHubStatus { get; set; }
        public DateTime? ClosedDate { get; set; }
    }
}
