// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ef8PowerTools.Data.Models
{
    public partial class TakedaHSCPortal_Get_ServiceRequestResult
    {
        public int ServiceRequestID { get; set; }
        public int SR_TypeListID { get; set; }
        public string SR_TypeFullDesc { get; set; }
        public string SR_TypeShortDesc { get; set; }
        public int? PatientID { get; set; }
        public int? PhysicianID { get; set; }
        public int? OrganizationID { get; set; }
        public int? ContactID { get; set; }
        public string FirstName_Pat { get; set; }
        public string LastName_Pat { get; set; }
        public string FullName_Pat { get; set; }
        public string FirstName_Phy { get; set; }
        public string LastName_Phy { get; set; }
        public string FullName_phy { get; set; }
        public string FirstName_Contact { get; set; }
        public string LastName_Contact { get; set; }
        public string FullName_Contact { get; set; }
        public string OrganizationName { get; set; }
    }
}
