// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class TamtrackerColor
{
    public int ColorId { get; set; }

    public string ColorName { get; set; }

    public string ColorCode { get; set; }

    public int? SortOrder { get; set; }

    public DateTime? Created { get; set; }

    public string Createdby { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedby { get; set; }

    public bool? Deleted { get; set; }

    public bool? Active { get; set; }

    public int ProgramId { get; set; }
}