// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class VendorApimethodConfiguration
{
    public int VendorApimethodConfigurationId { get; set; }

    public int ProgramId { get; set; }

    public int VendorId { get; set; }

    public string TriggerRule { get; set; }

    public int? SrtypeListId { get; set; }

    public int? SrsubTypeListId { get; set; }

    public string Apimethod { get; set; }

    public string Httpmethod { get; set; }

    public bool Deleted { get; set; }

    public bool Active { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }
}