// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ef8PowerTools.Data.Models
{
    public partial class VeronaPortal_GetDocumentByDocumentIdResult
    {
        public string FileName { get; set; }
        public long? FileSize { get; set; }
        public byte[] FileData { get; set; }
        public string ContentType { get; set; }
        public int? EntityID { get; set; }
    }
}
