// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class VwPatientDataV2
{
    public int PatientId { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string Gender { get; set; }

    public DateOnly? Dob { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string AptSuite { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zipcode { get; set; }

    public string HomePhone { get; set; }

    public string CellPhone { get; set; }

    public string PreferredTime { get; set; }

    public string PreferredLanguage { get; set; }

    public string PreferredPhone { get; set; }

    public string PreferredPhoneType { get; set; }

    public string Paptype { get; set; }

    public int ProgramId { get; set; }

    public int ServiceRequestId { get; set; }

    public string ContactFirstName { get; set; }

    public string ContactLastName { get; set; }

    public string RelationshipToPatient { get; set; }
}