// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class VwWorkflowEmail
{
    public Guid WorkflowProgramEmailId { get; set; }

    public Guid WorkflowId { get; set; }

    public Guid? WorkflowTypeId { get; set; }

    public string EmailSubject { get; set; }

    public Guid? WorkflowProgramEmailType { get; set; }

    public string Cclist { get; set; }

    public string Bcclist { get; set; }

    public string BodyText { get; set; }

    public bool? IsActive { get; set; }

    public Guid LookupItemId { get; set; }

    public Guid LookupId { get; set; }

    public string Paptype { get; set; }

    public string LookupDisplay { get; set; }

    public short? Sequence { get; set; }

    public bool LookupItemActive { get; set; }

    public string LookupItemTag { get; set; }

    public string LookupName { get; set; }

    public string Description { get; set; }

    public bool WorkflowLookupsIsActive { get; set; }

    public string EmailType { get; set; }
}