// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class WorkflowPaptypeConfig
{
    public Guid WorkflowPaptypeConfigId { get; set; }

    public Guid WorkFlowId { get; set; }

    public Guid PaptypeItemId { get; set; }

    public Guid DefaultPaptypeItemId { get; set; }

    public bool? Deleted { get; set; }

    public bool? Active { get; set; }

    public DateTime Created { get; set; }

    public string Createdby { get; set; }

    public DateTime? LastUpdated { get; set; }

    public bool? LatUpdatedby { get; set; }
}