// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models;

public partial class ZipCode
{
    public string ZipCode1 { get; set; }

    public string County { get; set; }

    public string City { get; set; }

    public string State { get; set; }
}