// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class BenefitInvestigationTypeFieldConfiguration : IEntityTypeConfiguration<BenefitInvestigationTypeField>
    {
        public void Configure(EntityTypeBuilder<BenefitInvestigationTypeField> entity)
        {
            entity.HasKey(e => e.BenefitInvestigationTypeFieldsId);

            entity.Property(e => e.BenefitInvestigationTypeFieldsId).HasColumnName("BenefitInvestigationTypeFieldsID");
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.AllowNa).HasColumnName("AllowNA");
            entity.Property(e => e.BenefitHistoryFieldListId).HasColumnName("BenefitHistoryFieldListID");
            entity.Property(e => e.BenefitInvestigationType)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Created)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Description)
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.FieldDisplay)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.LastUpdated).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");
            entity.Property(e => e.Required)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.SortOrder).HasColumnType("decimal(18, 2)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BenefitInvestigationTypeField> entity);
    }
}
