// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class BiNdcRecordConfiguration : IEntityTypeConfiguration<BiNdcRecord>
    {
        public void Configure(EntityTypeBuilder<BiNdcRecord> entity)
        {
            entity.ToTable("BI_NDC_Records");

            entity.HasIndex(e => new { e.ProgramId, e.Deleted, e.ServiceRequestId }, "IX_ServiceRequestID");

            entity.Property(e => e.BiNdcRecordId).HasColumnName("BI_NDC_RecordID");
            entity.Property(e => e.BenefitInvestigationId).HasColumnName("BenefitInvestigationID");
            entity.Property(e => e.Bitype)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("BIType");
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastUpdated).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.OriginalId).HasColumnName("OriginalID");
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");
            entity.Property(e => e.ServiceRequestId).HasColumnName("ServiceRequestID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BiNdcRecord> entity);
    }
}
