// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class CareCyclesAuditConfiguration : IEntityTypeConfiguration<CareCyclesAudit>
    {
        public void Configure(EntityTypeBuilder<CareCyclesAudit> entity)
        {
            entity
                .HasNoKey()
                .ToTable("CareCycles_Audit");

            entity.Property(e => e.CareCycleEndDate).HasColumnType("datetime");
            entity.Property(e => e.CareCycleEndedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CareCycleId).HasColumnName("CareCycleID");
            entity.Property(e => e.CareCycleStartDate).HasColumnType("datetime");
            entity.Property(e => e.CareCycleStartedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CareCycleState)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CareCycleStatus)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.CareCycleTypeCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CareCyclesAuditId)
                .ValueGeneratedOnAdd()
                .HasColumnName("CareCycles_AuditID");
            entity.Property(e => e.ChangeAction)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Change_Action");
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedByLog)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("CreatedBy_log");
            entity.Property(e => e.CreatedLog)
                .HasColumnType("datetime")
                .HasColumnName("Created_log");
            entity.Property(e => e.Custom1FieldLabel)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Custom1_FieldLabel");
            entity.Property(e => e.Custom1FieldValue)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Custom1_FieldValue");
            entity.Property(e => e.DrugTherapy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ExternalId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ExternalID");
            entity.Property(e => e.ExternalId2)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ExternalID2");
            entity.Property(e => e.LastUpdated).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LegacyId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("LegacyID");
            entity.Property(e => e.OrganizationId).HasColumnName("OrganizationID");
            entity.Property(e => e.OrganizationLocationId).HasColumnName("OrganizationLocationID");
            entity.Property(e => e.PatientHubStatus)
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.PatientHubStatusDate).HasColumnType("datetime");
            entity.Property(e => e.PatientId).HasColumnName("PatientID");
            entity.Property(e => e.PatientLocationId).HasColumnName("PatientLocationID");
            entity.Property(e => e.PatientOtherStatusType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PatientOtherStatusValue)
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.PatientSpstatus)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("PatientSPStatus");
            entity.Property(e => e.PatientSpstatusDate)
                .HasColumnType("datetime")
                .HasColumnName("PatientSPStatusDate");
            entity.Property(e => e.PhysicianId).HasColumnName("PhysicianID");
            entity.Property(e => e.PhysicianLocationId).HasColumnName("PhysicianLocationID");
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");
            entity.Property(e => e.Source)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CareCyclesAudit> entity);
    }
}
