// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class ConnectFedexApierrorLogConfiguration : IEntityTypeConfiguration<ConnectFedexApierrorLog>
    {
        public void Configure(EntityTypeBuilder<ConnectFedexApierrorLog> entity)
        {
            entity.HasKey(e => e.ConnectFedexApierrorLogId).HasName("PK_ConnectFedexAPIErrorLog");

            entity.ToTable("ConnectFedexAPIErrorLogs");

            entity.Property(e => e.ConnectFedexApierrorLogId).HasColumnName("ConnectFedexAPIErrorLogID");
            entity.Property(e => e.ApplicationName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ErrorLogIdkeysReturn)
                .IsRequired()
                .IsUnicode(false)
                .HasDefaultValue("")
                .HasColumnName("ErrorLogIDKeysReturn");
            entity.Property(e => e.ErrorMessage)
                .IsRequired()
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ExceptionMessage)
                .IsRequired()
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ScreenName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.UpdatedByIdkey).HasColumnName("UpdatedByIDKey");
            entity.Property(e => e.UpdatedDt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ConnectFedexApierrorLog> entity);
    }
}
