// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class CrossdbPortalAccountProgramConfiguration : IEntityTypeConfiguration<CrossdbPortalAccountProgram>
    {
        public void Configure(EntityTypeBuilder<CrossdbPortalAccountProgram> entity)
        {
            entity
                .HasNoKey()
                .ToView("crossdb_PortalAccountPrograms");

            entity.Property(e => e.AccountId).HasColumnName("AccountID");
            entity.Property(e => e.CareMetxRecordId).HasColumnName("CareMetxRecordID");
            entity.Property(e => e.CareMetxRecordType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CrossdbPortalAccountProgram> entity);
    }
}
