// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class DashboardPanelListConfiguration : IEntityTypeConfiguration<DashboardPanelList>
    {
        public void Configure(EntityTypeBuilder<DashboardPanelList> entity)
        {
            entity.ToTable("DashboardPanelList");

            entity.Property(e => e.DashboardPanelListId)
                .ValueGeneratedNever()
                .HasColumnName("DashboardPanelListID");
            entity.Property(e => e.Description)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Panel)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PanelType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("Table");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DashboardPanelList> entity);
    }
}
