// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class DataDictionaryConfiguration : IEntityTypeConfiguration<DataDictionary>
    {
        public void Configure(EntityTypeBuilder<DataDictionary> entity)
        {
            entity.HasKey(e => e.DataDictionaryId).HasName("PK_Table_1");

            entity.ToTable("DataDictionary");

            entity.Property(e => e.DataDictionaryId).HasColumnName("DataDictionaryID");
            entity.Property(e => e.DataArea)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DataName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.FieldName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FieldStorageType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FlagToDisplay)
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.FunctionName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.RequiredforSrclose).HasColumnName("RequiredforSRClose");
            entity.Property(e => e.RequiredforSrcreation).HasColumnName("RequiredforSRCreation");
            entity.Property(e => e.SortOrder).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.TableName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Tooltip)
                .HasMaxLength(500)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DataDictionary> entity);
    }
}
