// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class DatabasechangelogConfiguration : IEntityTypeConfiguration<Databasechangelog>
    {
        public void Configure(EntityTypeBuilder<Databasechangelog> entity)
        {
            entity
                .HasNoKey()
                .ToTable("DATABASECHANGELOG");

            entity.Property(e => e.Author)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("AUTHOR");
            entity.Property(e => e.Comments)
                .HasMaxLength(255)
                .HasColumnName("COMMENTS");
            entity.Property(e => e.Contexts)
                .HasMaxLength(255)
                .HasColumnName("CONTEXTS");
            entity.Property(e => e.Dateexecuted)
                .HasPrecision(3)
                .HasColumnName("DATEEXECUTED");
            entity.Property(e => e.DeploymentId)
                .HasMaxLength(10)
                .HasColumnName("DEPLOYMENT_ID");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasColumnName("DESCRIPTION");
            entity.Property(e => e.Exectype)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("EXECTYPE");
            entity.Property(e => e.Filename)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("FILENAME");
            entity.Property(e => e.Id)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("ID");
            entity.Property(e => e.Labels)
                .HasMaxLength(255)
                .HasColumnName("LABELS");
            entity.Property(e => e.Liquibase)
                .HasMaxLength(20)
                .HasColumnName("LIQUIBASE");
            entity.Property(e => e.Md5sum)
                .HasMaxLength(35)
                .HasColumnName("MD5SUM");
            entity.Property(e => e.Orderexecuted).HasColumnName("ORDEREXECUTED");
            entity.Property(e => e.Tag)
                .HasMaxLength(255)
                .HasColumnName("TAG");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Databasechangelog> entity);
    }
}
