// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class DfEmailLogConfiguration : IEntityTypeConfiguration<DfEmailLog>
    {
        public void Configure(EntityTypeBuilder<DfEmailLog> entity)
        {
            entity.ToTable("DF_EmailLog");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EmailBody).HasColumnType("text");
            entity.Property(e => e.EmailStatus)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EmailSubject)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.EmailTo)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EventType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.JobRootPid)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Job_root_pid");
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");
            entity.Property(e => e.RecordId).HasColumnName("RecordID");
            entity.Property(e => e.RecordType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ServiceRequestId).HasColumnName("ServiceRequestID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DfEmailLog> entity);
    }
}
