// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class DispenseOrderTypeConfiguration : IEntityTypeConfiguration<DispenseOrderType>
    {
        public void Configure(EntityTypeBuilder<DispenseOrderType> entity)
        {
            entity.HasNoKey();

            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.Createdby)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastUpdated).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedby)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.OrderType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.OrderTypeCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Pkid)
                .ValueGeneratedOnAdd()
                .HasColumnName("pkid");
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DispenseOrderType> entity);
    }
}
