// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class DocumentsOcrDynamicDatumConfiguration : IEntityTypeConfiguration<DocumentsOcrDynamicDatum>
    {
        public void Configure(EntityTypeBuilder<DocumentsOcrDynamicDatum> entity)
        {
            entity.HasKey(e => e.DocumentsOcrDynamicDataId).HasName("PK__Document__39CAE9F91F458EE6");

            entity.ToTable("Documents_OCR_DynamicData");

            entity.Property(e => e.DocumentsOcrDynamicDataId).HasColumnName("Documents_OCR_DynamicDataID");
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DocumentsOcrCoordinatesId).HasColumnName("Documents_OCR_CoordinatesID");
            entity.Property(e => e.FieldKey)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.FieldValue).IsUnicode(false);
            entity.Property(e => e.InboundFaxId).HasColumnName("InboundFaxID");
            entity.Property(e => e.IsSelected).HasDefaultValue(false);
            entity.Property(e => e.LastUpdated).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DocumentsOcrDynamicDatum> entity);
    }
}
