// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class DocumentsMoveAuditConfiguration : IEntityTypeConfiguration<DocumentsMoveAudit>
    {
        public void Configure(EntityTypeBuilder<DocumentsMoveAudit> entity)
        {
            entity.HasKey(e => e.DocumentMoveAuditId);

            entity.ToTable("Documents_MoveAudits");

            entity.Property(e => e.DocumentMoveAuditId).HasColumnName("Document_MoveAudit_ID");
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DocumentId).HasColumnName("DocumentID");
            entity.Property(e => e.MoveFromEntityId).HasColumnName("MoveFromEntityID");
            entity.Property(e => e.MoveToEntityId).HasColumnName("MoveToEntityID");
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");
            entity.Property(e => e.ReasonMoved)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DocumentsMoveAudit> entity);
    }
}
