// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class DocumentListLetterConfiguration : IEntityTypeConfiguration<DocumentListLetter>
    {
        public void Configure(EntityTypeBuilder<DocumentListLetter> entity)
        {
            entity.HasKey(e => e.DocumentListId).HasName("PK__Document__6E25082060B57663");

            entity.ToTable("DocumentListLetter");

            entity.Property(e => e.DocumentListId).ValueGeneratedNever();
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Header)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.LastUpdatedBy).HasMaxLength(50);
            entity.Property(e => e.LetterNumber)
                .IsRequired()
                .HasMaxLength(5)
                .IsUnicode(false);

            entity.HasOne(d => d.DocumentList).WithOne(p => p.DocumentListLetter)
                .HasForeignKey<DocumentListLetter>(d => d.DocumentListId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DocumentListID_DocumentList");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DocumentListLetter> entity);
    }
}
