// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class DocumentsTherapyDrugConfiguration : IEntityTypeConfiguration<DocumentsTherapyDrug>
    {
        public void Configure(EntityTypeBuilder<DocumentsTherapyDrug> entity)
        {
            entity.HasKey(e => new { e.DocumentListId, e.TherapyDrug }).HasName("PK_Documents_TherapyDrugs_1");

            entity.ToTable("Documents_TherapyDrugs");

            entity.Property(e => e.DocumentListId).HasColumnName("DocumentListID");
            entity.Property(e => e.TherapyDrug)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.DocumentList).WithMany(p => p.DocumentsTherapyDrugs)
                .HasForeignKey(d => d.DocumentListId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Documents_TherapyDrugs_DocumentList");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DocumentsTherapyDrug> entity);
    }
}
