// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class EbvmedicalResponseTypeCodeConfiguration : IEntityTypeConfiguration<EbvmedicalResponseTypeCode>
    {
        public void Configure(EntityTypeBuilder<EbvmedicalResponseTypeCode> entity)
        {
            entity.HasKey(e => e.EbvmedicalResponseTypeCodeId).HasName("PK__EBVMedic__124355B4B97AA110");

            entity.ToTable("EBVMedicalResponseTypeCode");

            entity.Property(e => e.EbvmedicalResponseTypeCodeId).HasColumnName("EBVMedicalResponseTypeCodeId");
            entity.Property(e => e.CompletionStatus)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Created)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Deleted).HasDefaultValue(false);
            entity.Property(e => e.EligibilityStatus)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.IsOfframpResponseCode).HasDefaultValue(false);
            entity.Property(e => e.LastUpdated).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.NumberOfPayers)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PlanTypes)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.ResponseTypeCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EbvmedicalResponseTypeCode> entity);
    }
}
