// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class EBvResourceLinkConfiguration : IEntityTypeConfiguration<EBvResourceLink>
    {
        public void Configure(EntityTypeBuilder<EBvResourceLink> entity)
        {
            entity.ToTable("eBvResourceLink");

            entity.Property(e => e.EBvResourceLinkId).HasColumnName("eBvResourceLinkID");
            entity.Property(e => e.EBvCoverageFactorsId).HasColumnName("eBvCoverageFactorsID");
            entity.Property(e => e.ResourceLinkMessage)
                .HasMaxLength(265)
                .IsUnicode(false);
            entity.Property(e => e.ResourceLinkMessageType)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.EBvCoverageFactors).WithMany(p => p.EBvResourceLinks)
                .HasForeignKey(d => d.EBvCoverageFactorsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_eBvResourceLink_eBvCoverageFactors");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EBvResourceLink> entity);
    }
}
