// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class EpapApplicationConfiguration : IEntityTypeConfiguration<EpapApplication>
    {
        public void Configure(EntityTypeBuilder<EpapApplication> entity)
        {
            entity.HasKey(e => e.ApplicationId).HasName("Pk_Applications_application_id");

            entity.ToTable("EPAP_Applications", tb => tb.HasComment("The ePap application"));

            entity.Property(e => e.ApplicationId)
                .ValueGeneratedNever()
                .HasComment("The primary key")
                .HasColumnName("ApplicationID");
            entity.Property(e => e.ApplicationState).HasComment("The application state where the lookup is APPLICATION_STATES");
            entity.Property(e => e.Created)
                .HasComment("The created timestamp")
                .HasColumnType("datetime");
            entity.Property(e => e.InvitationId)
                .HasComment("The invitation id")
                .HasColumnName("InvitationID");
            entity.Property(e => e.ProgramId)
                .HasComment("The program id")
                .HasColumnName("ProgramID");
            entity.Property(e => e.ScreenName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Invitation).WithMany(p => p.EpapApplications)
                .HasForeignKey(d => d.InvitationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EPapApplications_Invitations");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EpapApplication> entity);
    }
}
