// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class FaxLogExceptionConfiguration : IEntityTypeConfiguration<FaxLogException>
    {
        public void Configure(EntityTypeBuilder<FaxLogException> entity)
        {
            entity.HasKey(e => e.FleId).HasName("PK__FAX_LOG___ADE5768D15502E78");

            entity.ToTable("FAX_LOG_EXCEPTIONS");

            entity.Property(e => e.FleId).HasColumnName("FLE_ID");
            entity.Property(e => e.FleCreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("FLE_CREATED_DATE");
            entity.Property(e => e.FleErrorMessageText)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("FLE_ERROR_MESSAGE_TEXT");
            entity.Property(e => e.FleFldId).HasColumnName("FLE_FLD_ID");
            entity.Property(e => e.FleFlsId).HasColumnName("FLE_FLS_ID");
            entity.Property(e => e.FleStackTraceText)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("FLE_STACK_TRACE_TEXT");

            entity.HasOne(d => d.FleFld).WithMany(p => p.FaxLogExceptions)
                .HasForeignKey(d => d.FleFldId)
                .HasConstraintName("FK_FAX_LOG_EXCEPTIONS_FAX_LOG_DETAILS");

            entity.HasOne(d => d.FleFls).WithMany(p => p.FaxLogExceptions)
                .HasForeignKey(d => d.FleFlsId)
                .HasConstraintName("FLE_FLS_FK");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FaxLogException> entity);
    }
}
