// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class FundReopenSubscriptionMedicationConfiguration : IEntityTypeConfiguration<FundReopenSubscriptionMedication>
    {
        public void Configure(EntityTypeBuilder<FundReopenSubscriptionMedication> entity)
        {
            entity.Property(e => e.FundReopenSubscriptionMedicationId).HasColumnName("FundReopenSubscriptionMedicationID");
            entity.Property(e => e.Created)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DrugId).HasColumnName("DrugID");
            entity.Property(e => e.DrugName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.Subscription).WithMany(p => p.FundReopenSubscriptionMedications)
                .HasForeignKey(d => d.SubscriptionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FundReopenSubscriptionMedications_FundReopenSubscriptionDetails");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FundReopenSubscriptionMedication> entity);
    }
}
