// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class Log4NetErrorConfiguration : IEntityTypeConfiguration<Log4NetError>
    {
        public void Configure(EntityTypeBuilder<Log4NetError> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_log4net_error");

            entity.ToTable("Log4Net_Error");

            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.Exception)
                .HasMaxLength(4000)
                .IsUnicode(false);
            entity.Property(e => e.Level)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Logger)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Message)
                .IsRequired()
                .HasMaxLength(4000)
                .IsUnicode(false);
            entity.Property(e => e.Thread)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Log4NetError> entity);
    }
}
