// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class LtrMailTransactionConfiguration : IEntityTypeConfiguration<LtrMailTransaction>
    {
        public void Configure(EntityTypeBuilder<LtrMailTransaction> entity)
        {
            entity.HasKey(e => e.MailNotificationId);

            entity.ToTable("LTR_MailTransaction");

            entity.Property(e => e.MailNotificationId)
                .ValueGeneratedNever()
                .HasColumnName("MailNotificationID");
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Event)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EventTimeStamp).HasColumnType("datetime");
            entity.Property(e => e.ExternalId).HasColumnName("ExternalID");
            entity.Property(e => e.ExternalMessage).IsUnicode(false);
            entity.Property(e => e.MailTransactionId)
                .ValueGeneratedOnAdd()
                .HasColumnName("MailTransactionID");
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");

            entity.HasOne(d => d.MailNotification).WithOne(p => p.LtrMailTransaction)
                .HasForeignKey<LtrMailTransaction>(d => d.MailNotificationId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LtrMailTransaction> entity);
    }
}
