// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class MobilePatientSurveyAnswerConfiguration : IEntityTypeConfiguration<MobilePatientSurveyAnswer>
    {
        public void Configure(EntityTypeBuilder<MobilePatientSurveyAnswer> entity)
        {
            entity.Property(e => e.MobilePatientSurveyAnswerId).HasColumnName("MobilePatientSurveyAnswerID");
            entity.Property(e => e.AnswerText)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastUpdated).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LookupDataListId).HasColumnName("LookupDataListID");
            entity.Property(e => e.MobileDrugSurveyElementId).HasColumnName("MobileDrugSurveyElementID");
            entity.Property(e => e.MobilePatientSurveyAnswerMasterId).HasColumnName("MobilePatientSurveyAnswerMasterID");
            entity.Property(e => e.MobileSurveySubElementId).HasColumnName("MobileSurveySubElementID");
            entity.Property(e => e.PatientId).HasColumnName("PatientID");
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");

            entity.HasOne(d => d.MobileDrugSurveyElement).WithMany(p => p.MobilePatientSurveyAnswers)
                .HasForeignKey(d => d.MobileDrugSurveyElementId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MobilePatientSurveyAnswers_MobileDrugSurveyElements");

            entity.HasOne(d => d.MobilePatientSurveyAnswerMaster).WithMany(p => p.MobilePatientSurveyAnswers)
                .HasForeignKey(d => d.MobilePatientSurveyAnswerMasterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MobilePatientSurveyAnswers_MobilePatientSurveyAnswerMaster");

            entity.HasOne(d => d.MobileSurveySubElement).WithMany(p => p.MobilePatientSurveyAnswers)
                .HasForeignKey(d => d.MobileSurveySubElementId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MobilePatientSurveyAnswers_MobileSurveyAnswers");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MobilePatientSurveyAnswer> entity);
    }
}
