// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class MpuAssessmentDetailConfiguration : IEntityTypeConfiguration<MpuAssessmentDetail>
    {
        public void Configure(EntityTypeBuilder<MpuAssessmentDetail> entity)
        {
            entity
                .HasNoKey()
                .ToTable("MPU_Assessment_Detail");

            entity.Property(e => e.AssessmentDetailId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("assessment_detail_id");
            entity.Property(e => e.AssessmentId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("assessment_id");
            entity.Property(e => e.AssessmentQuestionId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("assessment_question_id");
            entity.Property(e => e.AssessmentQuestionScore)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("assessment_question_score");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MpuAssessmentDetail> entity);
    }
}
