// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class PanDisenrollmentReversalConfiguration : IEntityTypeConfiguration<PanDisenrollmentReversal>
    {
        public void Configure(EntityTypeBuilder<PanDisenrollmentReversal> entity)
        {
            entity.HasKey(e => e.DisenrollmentReversalId).IsClustered(false);

            entity.ToTable("PAN_DisenrollmentReversal", tb => tb.HasTrigger("utPAN_DisenrollmentReversal"));

            entity.Property(e => e.ContactedPan).HasColumnName("ContactedPAN");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.FinalizedBy).HasMaxLength(50);
            entity.Property(e => e.LastUpdatedBy).HasMaxLength(50);
            entity.Property(e => e.PanfundDecision).HasColumnName("PANFundDecision");
            entity.Property(e => e.PanfundRequestDate).HasColumnName("PANFundRequestDate");
            entity.Property(e => e.PanfundResponseDate).HasColumnName("PANFundResponseDate");
            entity.Property(e => e.PanreceivedDate).HasColumnName("PANReceivedDate");
            entity.Property(e => e.PanrequestedDate).HasColumnName("PANRequestedDate");
            entity.Property(e => e.ResultMessage).HasMaxLength(300);
            entity.Property(e => e.ReversalNotes).HasMaxLength(1000);
            entity.Property(e => e.SubmittedBy).HasMaxLength(50);

            entity.HasOne(d => d.Status).WithMany(p => p.PanDisenrollmentReversals)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PAN_DisenrollmentReversal_StatusId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PanDisenrollmentReversal> entity);
    }
}
