// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class PatientDupeSearchResponseConfiguration : IEntityTypeConfiguration<PatientDupeSearchResponse>
    {
        public void Configure(EntityTypeBuilder<PatientDupeSearchResponse> entity)
        {
            entity.Property(e => e.PatientDupeSearchResponseId).HasColumnName("PatientDupeSearchResponseID");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Dob)
                .HasColumnType("datetime")
                .HasColumnName("DOB");
            entity.Property(e => e.EntityDupeSearchRequestId).HasColumnName("EntityDupeSearchRequestID");
            entity.Property(e => e.ExternalId)
                .HasMaxLength(50)
                .HasColumnName("ExternalID");
            entity.Property(e => e.FirstName).HasMaxLength(100);
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.MatchScore)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.PatientId).HasColumnName("PatientID");
            entity.Property(e => e.Ssn)
                .HasMaxLength(50)
                .HasColumnName("SSN");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.UpdatedOn).HasColumnType("datetime");
            entity.Property(e => e.Zip)
                .HasMaxLength(50)
                .HasColumnName("ZIP");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PatientDupeSearchResponse> entity);
    }
}
