// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class PatientStatusProgramListConfiguration : IEntityTypeConfiguration<PatientStatusProgramList>
    {
        public void Configure(EntityTypeBuilder<PatientStatusProgramList> entity)
        {
            entity.HasKey(e => e.ProgramPatientStatusListId).HasName("PK_ProgramPatientStatusList");

            entity.ToTable("PatientStatusProgramList");

            entity.Property(e => e.ProgramPatientStatusListId).HasColumnName("ProgramPatientStatusListID");
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.Created)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PatientStatusListId).HasColumnName("PatientStatusListID");
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");
            entity.Property(e => e.SortOrder).HasColumnType("decimal(6, 2)");

            entity.HasOne(d => d.PatientStatusList).WithMany(p => p.PatientStatusProgramLists)
                .HasForeignKey(d => d.PatientStatusListId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProgramPatientStatusList_PatientStatusList");

            entity.HasOne(d => d.Program).WithMany(p => p.PatientStatusProgramLists)
                .HasForeignKey(d => d.ProgramId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProgramPatientStatusList_Programs");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PatientStatusProgramList> entity);
    }
}
