// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class PhysiciansDetailConfiguration : IEntityTypeConfiguration<PhysiciansDetail>
    {
        public void Configure(EntityTypeBuilder<PhysiciansDetail> entity)
        {
            entity.ToTable("PhysiciansDetail", tb =>
                {
                    tb.HasTrigger("Tr_PhysiciansDetail_Audit_Insert");
                    tb.HasTrigger("Tr_PhysiciansDetail_Audit_Update");
                });

            entity.Property(e => e.PhysiciansDetailId).HasColumnName("PhysiciansDetailID");
            entity.Property(e => e.Bcbsid)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("BCBSID");
            entity.Property(e => e.Created)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Data2000WaiverXdea)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Data2000WaiverXDEA");
            entity.Property(e => e.Dea)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("DEA");
            entity.Property(e => e.ExternalId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ExternalID");
            entity.Property(e => e.Hin)
                .HasMaxLength(9)
                .IsUnicode(false)
                .HasColumnName("HIN");
            entity.Property(e => e.LastUpdated).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MedicaidId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("MedicaidID");
            entity.Property(e => e.MedicareId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("MedicareID");
            entity.Property(e => e.PhysicianId).HasColumnName("PhysicianID");
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");
            entity.Property(e => e.Ptan)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("PTAN");
            entity.Property(e => e.TaxId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("TaxID");

            entity.HasOne(d => d.Physician).WithMany(p => p.PhysiciansDetails)
                .HasForeignKey(d => d.PhysicianId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhysiciansDetail_Physicians");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PhysiciansDetail> entity);
    }
}
