// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class PortalHcpButtonsAuditLogConfiguration : IEntityTypeConfiguration<PortalHcpButtonsAuditLog>
    {
        public void Configure(EntityTypeBuilder<PortalHcpButtonsAuditLog> entity)
        {
            entity.HasKey(e => e.AuditId);

            entity.ToTable("Portal_HCP_Buttons_AuditLog");

            entity.Property(e => e.AuditId).HasColumnName("AuditID");
            entity.Property(e => e.ButtonName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ClickedBy)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ClickedOn).HasColumnType("datetime");
            entity.Property(e => e.IsStagingSr).HasColumnName("IsStagingSR");
            entity.Property(e => e.ServiceRequestId).HasColumnName("ServiceRequestID");
            entity.Property(e => e.UserName)
                .HasMaxLength(100)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PortalHcpButtonsAuditLog> entity);
    }
}
