// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class PortalAnnouncementConfiguration : IEntityTypeConfiguration<PortalAnnouncement>
    {
        public void Configure(EntityTypeBuilder<PortalAnnouncement> entity)
        {
            entity.ToTable("PortalAnnouncement");

            entity.Property(e => e.PortalAnnouncementId).HasColumnName("PortalAnnouncementID");
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.AnnouncementName)
                .HasMaxLength(5000)
                .IsUnicode(false);
            entity.Property(e => e.AnnouncementTypeCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Created)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.LastUpdated).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Portal)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");
            entity.Property(e => e.StartDate).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PortalAnnouncement> entity);
    }
}
