// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class PortalDataLoadRecordConfiguration : IEntityTypeConfiguration<PortalDataLoadRecord>
    {
        public void Configure(EntityTypeBuilder<PortalDataLoadRecord> entity)
        {
            entity
                .HasNoKey()
                .ToTable("PortalData_LoadRecord");

            entity.HasIndex(e => e.LoadId, "IX_PortalData_LoadRecord_LoadID").IsUnique();

            entity.HasIndex(e => new { e.ProgramId, e.LoadId, e.Status, e.RegionId, e.TerritoryId }, "ProgramLoadID");

            entity.Property(e => e.ErrorMsg)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.IsError).HasColumnName("isError");
            entity.Property(e => e.LoadId).HasColumnName("LoadID");
            entity.Property(e => e.Pkid)
                .ValueGeneratedOnAdd()
                .HasColumnName("pkid");
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");
            entity.Property(e => e.RegionCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.RegionId).HasColumnName("RegionID");
            entity.Property(e => e.TerritoryCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TerritoryId).HasColumnName("TerritoryID");
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            entity.Property(e => e.UserName)
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PortalDataLoadRecord> entity);
    }
}
