// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class PortalZipToTerrMinimalStageConfiguration : IEntityTypeConfiguration<PortalZipToTerrMinimalStage>
    {
        public void Configure(EntityTypeBuilder<PortalZipToTerrMinimalStage> entity)
        {
            entity
                .HasNoKey()
                .ToTable("Portal_Zip_ToTerr_Minimal_Stage");

            entity.Property(e => e.TerrId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Terr_ID");
            entity.Property(e => e.Zip)
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PortalZipToTerrMinimalStage> entity);
    }
}
