// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class PortalRosterRelationConfiguration : IEntityTypeConfiguration<PortalRosterRelation>
    {
        public void Configure(EntityTypeBuilder<PortalRosterRelation> entity)
        {
            entity.ToTable("Portal_Roster_Relation");

            entity.Property(e => e.PortalRosterRelationId).HasColumnName("Portal_Roster_RelationID");
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FrmPortalRosterId).HasColumnName("FRM_Portal_RosterID");
            entity.Property(e => e.LastUpdated).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PaaPortalRosterId).HasColumnName("PAA_Portal_RosterID");
            entity.Property(e => e.Pamname)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("PAMName");
            entity.Property(e => e.Pasname)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("PASName");
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");

            entity.HasOne(d => d.FrmPortalRoster).WithMany(p => p.PortalRosterRelations)
                .HasForeignKey(d => d.FrmPortalRosterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Portal_Ro__FRM_P__3D807D68");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PortalRosterRelation> entity);
    }
}
