// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class PsiIcd9Configuration : IEntityTypeConfiguration<PsiIcd9>
    {
        public void Configure(EntityTypeBuilder<PsiIcd9> entity)
        {
            entity
                .HasNoKey()
                .ToTable("PSI_ICD9");

            entity.Property(e => e.Icd9)
                .HasMaxLength(255)
                .HasColumnName("ICD9");
            entity.Property(e => e.SpPatientId)
                .HasMaxLength(255)
                .HasColumnName("SP_PatientID");
            entity.Property(e => e.Yob)
                .HasMaxLength(255)
                .HasColumnName("YOB");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PsiIcd9> entity);
    }
}
