// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class QaRepPayerCriterionConfiguration : IEntityTypeConfiguration<QaRepPayerCriterion>
    {
        public void Configure(EntityTypeBuilder<QaRepPayerCriterion> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__QA_RepPa__3214EC07FE0CF88C");

            entity.ToTable("QA_RepPayer_Criteria");

            entity.Property(e => e.RepOrPayer).HasMaxLength(50);
            entity.Property(e => e.RepOrPayerId)
                .HasMaxLength(50)
                .HasColumnName("RepOrPayerID");
            entity.Property(e => e.SrcloseDate).HasColumnName("SRCloseDate");
            entity.Property(e => e.Srcount).HasColumnName("SRCount");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<QaRepPayerCriterion> entity);
    }
}
