// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class Rimguij2UnqDrugJrnlConfiguration : IEntityTypeConfiguration<Rimguij2UnqDrugJrnl>
    {
        public void Configure(EntityTypeBuilder<Rimguij2UnqDrugJrnl> entity)
        {
            entity.HasKey(e => new { e.Imguniqid, e.Imgstrtdt });

            entity.ToTable("RIMGUIJ2_UNQ_DRUG_JRNL");

            entity.Property(e => e.Imguniqid).HasColumnName("IMGUNIQID");
            entity.Property(e => e.Imgstrtdt).HasColumnName("IMGSTRTDT");
            entity.Property(e => e.Imgid).HasColumnName("IMGID");
            entity.Property(e => e.Imgstopdt).HasColumnName("IMGSTOPDT");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Rimguij2UnqDrugJrnl> entity);
    }
}
