// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class Rimgudg2UnqDrugConfiguration : IEntityTypeConfiguration<Rimgudg2UnqDrug>
    {
        public void Configure(EntityTypeBuilder<Rimgudg2UnqDrug> entity)
        {
            entity.HasKey(e => e.Imguniqid);

            entity.ToTable("RIMGUDG2_UNQ_DRUG");

            entity.Property(e => e.Imguniqid).HasColumnName("IMGUNIQID");
            entity.Property(e => e.Imgdfid).HasColumnName("IMGDFID");
            entity.Property(e => e.Imgmfgid).HasColumnName("IMGMFGID");
            entity.Property(e => e.Imgndc)
                .HasMaxLength(20)
                .HasColumnName("IMGNDC");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Rimgudg2UnqDrug> entity);
    }
}
