// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class RiteAidHourConfiguration : IEntityTypeConfiguration<RiteAidHour>
    {
        public void Configure(EntityTypeBuilder<RiteAidHour> entity)
        {
            entity.HasKey(e => e.RiteAidHoursId);

            entity.Property(e => e.RiteAidHoursId).HasColumnName("RiteAidHoursID");
            entity.Property(e => e.DayofWeek)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.OpenClosed)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RiteAidHour> entity);
    }
}
