// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class Rtmmid1TmMedConfiguration : IEntityTypeConfiguration<Rtmmid1TmMed>
    {
        public void Configure(EntityTypeBuilder<Rtmmid1TmMed> entity)
        {
            entity
                .HasNoKey()
                .ToTable("RTMMID1_TM_MED");

            entity.Property(e => e.Medid).HasColumnName("MEDID");
            entity.Property(e => e.TmAltMedidDesc)
                .HasMaxLength(70)
                .HasColumnName("TM_ALT_MEDID_DESC");
            entity.Property(e => e.TmInd).HasColumnName("TM_IND");
            entity.Property(e => e.TmSourceId).HasColumnName("TM_SOURCE_ID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Rtmmid1TmMed> entity);
    }
}
