// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class SrBridgeEligibilityAuditLogConfiguration : IEntityTypeConfiguration<SrBridgeEligibilityAuditLog>
    {
        public void Configure(EntityTypeBuilder<SrBridgeEligibilityAuditLog> entity)
        {
            entity.HasKey(e => e.SrBridgeEligibilityAuditLogId).HasName("PK__SR_Bridg__3F8620403AF9E1CF");

            entity.ToTable("SR_BridgeEligibility_AuditLog");

            entity.Property(e => e.SrBridgeEligibilityAuditLogId).HasColumnName("SR_BridgeEligibility_AuditLogID");
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastUpdated).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LogCreated).HasColumnType("datetime");
            entity.Property(e => e.LogCreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MedicalExpense).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PatientId).HasColumnName("PatientID");
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");
            entity.Property(e => e.ServiceRequestId).HasColumnName("ServiceRequestID");
            entity.Property(e => e.SrBridgeEligibilityId).HasColumnName("SR_BridgeEligibilityID");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.StatusBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.StatusDate).HasColumnType("datetime");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SrBridgeEligibilityAuditLog> entity);
    }
}
