// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class SrNursingActivityConfiguration : IEntityTypeConfiguration<SrNursingActivity>
    {
        public void Configure(EntityTypeBuilder<SrNursingActivity> entity)
        {
            entity.HasKey(e => e.SrNursingActivityId).HasName("PK__SR_Nursi__CB9F1DE643B7AE54");

            entity.ToTable("SR_NursingActivity", tb => tb.HasTrigger("tr_update_sr_nursingactivity"));

            entity.HasIndex(e => new { e.ProgramId, e.Deleted, e.Status }, "<SR_NursingActivity_SRIDPatientIDActivity>");

            entity.Property(e => e.SrNursingActivityId).HasColumnName("SR_NursingActivityID");
            entity.Property(e => e.AcceptedEducationVisit)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.ActivityCompletedDate).HasColumnType("datetime");
            entity.Property(e => e.ActivityDueDate).HasColumnType("datetime");
            entity.Property(e => e.ActivityId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ActivityID");
            entity.Property(e => e.ActivityMode)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.ActivityType)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.AnsweredDocumentedQuestions)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.AskedPatientCall)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.CartrigesOrdered)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.CartrigesReceived)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.Comments).IsUnicode(false);
            entity.Property(e => e.ContactId).HasColumnName("ContactID");
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Dose).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DrugAdministered)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.ExplainedOrders)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.Frequency)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.FrequencyInterval)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FrequencyMin)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastUpdated).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MedicationReceived)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.NeedlesReceived)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.OfficeSubmitMaintenance)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.OptimalUse)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.PatientId).HasColumnName("PatientID");
            entity.Property(e => e.PatientKitReceived)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.PenPakOrdered)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.PenPakReceived)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.PredefinedComments)
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");
            entity.Property(e => e.RelatedTo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ServiceRequestId).HasColumnName("ServiceRequestID");
            entity.Property(e => e.SetExpectations)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.SharpsReceived)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Subject)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.SurveyHistoryId).HasColumnName("SurveyHistoryID");
            entity.Property(e => e.SwabsReveived)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.TiganReceived)
                .HasMaxLength(5)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SrNursingActivity> entity);
    }
}
