// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class SrOrderDetailConfiguration : IEntityTypeConfiguration<SrOrderDetail>
    {
        public void Configure(EntityTypeBuilder<SrOrderDetail> entity)
        {
            entity.HasKey(e => e.SrOrderDetailsId);

            entity.ToTable("SR_OrderDetails");

            entity.Property(e => e.SrOrderDetailsId).HasColumnName("SR_OrderDetailsID");
            entity.Property(e => e.ActivationExpirationDate).HasColumnType("datetime");
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastUpdated).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.OrderStatus)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PatientDeviceId).HasColumnName("PatientDeviceID");
            entity.Property(e => e.PatientRxDetailsId).HasColumnName("PatientRxDetailsID");
            entity.Property(e => e.PaymentAmount).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");
            entity.Property(e => e.ServiceRequestId).HasColumnName("ServiceRequestID");

            entity.HasOne(d => d.Program).WithMany(p => p.SrOrderDetails)
                .HasForeignKey(d => d.ProgramId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SR_OrderD__Progr__05905EA9");

            entity.HasOne(d => d.ServiceRequest).WithMany(p => p.SrOrderDetails)
                .HasForeignKey(d => d.ServiceRequestId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SR_OrderD__Servi__068482E2");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SrOrderDetail> entity);
    }
}
