// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class SrPappaymentConfiguration : IEntityTypeConfiguration<SrPappayment>
    {
        public void Configure(EntityTypeBuilder<SrPappayment> entity)
        {
            entity.HasKey(e => e.SrPappaymentId).HasName("PK_PAPPayments");

            entity.ToTable("SR_PAPPayments");

            entity.Property(e => e.SrPappaymentId).HasColumnName("SR_PAPPaymentID");
            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.CheckWrittenTo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Created)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastUpdated).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PayeeId).HasColumnName("PayeeID");
            entity.Property(e => e.PayeeName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");
            entity.Property(e => e.SrPappaymentScheduleId).HasColumnName("SR_PAPPaymentScheduleID");
            entity.Property(e => e.SrPapscheduledPaymentId).HasColumnName("SR_PAPScheduledPaymentID");
            entity.Property(e => e.Srid).HasColumnName("SRID");

            entity.HasOne(d => d.Program).WithMany(p => p.SrPappayments)
                .HasForeignKey(d => d.ProgramId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SR_PAPPayments_Programs");

            entity.HasOne(d => d.SrPapscheduledPayment).WithMany(p => p.SrPappayments)
                .HasForeignKey(d => d.SrPapscheduledPaymentId)
                .HasConstraintName("FK_SR_PAPPayments_SR_PAPScheduledPayments");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SrPappayment> entity);
    }
}
