// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class StateConfiguration : IEntityTypeConfiguration<State>
    {
        public void Configure(EntityTypeBuilder<State> entity)
        {
            entity.HasKey(e => e.Idusstate).HasName("PK__state__38D74042678A2F1F");

            entity.ToTable("state");

            entity.Property(e => e.Idusstate)
                .ValueGeneratedNever()
                .HasColumnName("idusstate");
            entity.Property(e => e.Usstatename)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("usstatename");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<State> entity);
    }
}
