// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class VendorApimethodConfigurationConfiguration : IEntityTypeConfiguration<VendorApimethodConfiguration>
    {
        public void Configure(EntityTypeBuilder<VendorApimethodConfiguration> entity)
        {
            entity
                .HasNoKey()
                .ToTable("Vendor_APIMethodConfiguration");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.Apimethod)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("APIMethod");
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Httpmethod)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("HTTPMethod");
            entity.Property(e => e.LastUpdated).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");
            entity.Property(e => e.SrsubTypeListId).HasColumnName("SRSubTypeListID");
            entity.Property(e => e.SrtypeListId).HasColumnName("SRTypeListID");
            entity.Property(e => e.TriggerRule)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.VendorApimethodConfigurationId)
                .ValueGeneratedOnAdd()
                .HasColumnName("Vendor_APIMethodConfigurationID");
            entity.Property(e => e.VendorId).HasColumnName("VendorID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VendorApimethodConfiguration> entity);
    }
}
