// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class VwBioMarinSrlistExcludeNonConsentedConfiguration : IEntityTypeConfiguration<VwBioMarinSrlistExcludeNonConsented>
    {
        public void Configure(EntityTypeBuilder<VwBioMarinSrlistExcludeNonConsented> entity)
        {
            entity
                .HasNoKey()
                .ToView("vw_BioMarinSRListExcludeNonConsented");

            entity.Property(e => e.Created)
                .HasColumnType("datetime")
                .HasColumnName("created");
            entity.Property(e => e.Lastupdated)
                .HasColumnType("datetime")
                .HasColumnName("lastupdated");
            entity.Property(e => e.ServiceRequestId).HasColumnName("ServiceRequestID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwBioMarinSrlistExcludeNonConsented> entity);
    }
}
