// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class VwGetPatientRecentLanguageConfiguration : IEntityTypeConfiguration<VwGetPatientRecentLanguage>
    {
        public void Configure(EntityTypeBuilder<VwGetPatientRecentLanguage> entity)
        {
            entity
                .HasNoKey()
                .ToView("vw_GetPatientRecentLanguage");

            entity.Property(e => e.Answer)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Category)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CssClass)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.DataType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.DynamicDataListId).HasColumnName("DynamicDataListID");
            entity.Property(e => e.DynamicDatalistCreated).HasColumnType("datetime");
            entity.Property(e => e.DynamicDatalistCreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FieldCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FieldLength)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FieldValidationMessage)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.FunctionName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LookUpDataListFunctionName)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.MaxValue)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MinValue)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PatientId).HasColumnName("PatientID");
            entity.Property(e => e.ProgramId).HasColumnName("ProgramID");
            entity.Property(e => e.RegularExpression)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Required)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.SortOrder).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Srtype)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("SRType");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwGetPatientRecentLanguage> entity);
    }
}
