// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class VwJjpfPhyFilterConfiguration : IEntityTypeConfiguration<VwJjpfPhyFilter>
    {
        public void Configure(EntityTypeBuilder<VwJjpfPhyFilter> entity)
        {
            entity
                .HasNoKey()
                .ToView("vw_JJPF_Phy_Filter");

            entity.Property(e => e.PhysicianId).HasColumnName("PhysicianID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwJjpfPhyFilter> entity);
    }
}
