// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class VwPatientHeigthWeightConfiguration : IEntityTypeConfiguration<VwPatientHeigthWeight>
    {
        public void Configure(EntityTypeBuilder<VwPatientHeigthWeight> entity)
        {
            entity
                .HasNoKey()
                .ToView("vw_PatientHeigthWeight");

            entity.Property(e => e.Height)
                .HasMaxLength(8000)
                .IsUnicode(false);
            entity.Property(e => e.PatientId).HasColumnName("patientId");
            entity.Property(e => e.ProgramId).HasColumnName("programId");
            entity.Property(e => e.ServiceRequestId).HasColumnName("ServiceRequestID");
            entity.Property(e => e.Weight)
                .HasMaxLength(8000)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwPatientHeigthWeight> entity);
    }
}
