// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ef8PowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ef8PowerTools.Data.Models.Configurations
{
    public partial class WorkflowStepProgramFieldConfiguration : IEntityTypeConfiguration<WorkflowStepProgramField>
    {
        public void Configure(EntityTypeBuilder<WorkflowStepProgramField> entity)
        {
            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.ProgramFieldId).HasColumnName("ProgramFieldID");
            entity.Property(e => e.ProgramWorkFlowStepId).HasColumnName("ProgramWorkFlowStepID");

            entity.HasOne(d => d.ProgramField).WithMany(p => p.WorkflowStepProgramFields)
                .HasForeignKey(d => d.ProgramFieldId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WorkflowStepProgramFields_WorkflowProgramFields");

            entity.HasOne(d => d.ProgramWorkFlowStep).WithMany(p => p.WorkflowStepProgramFields)
                .HasForeignKey(d => d.ProgramWorkFlowStepId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WorkflowStepProgramFields_WorkflowLookupItems");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WorkflowStepProgramField> entity);
    }
}
